  * Imóveis 
  * Cury 
  * Serviços 
  * Área do Cliente
  * São Paulo


  * São Paulo  Rio de Janeiro 


  * Imóveis 
Cury
  * Serviços
  *   * Área do Cliente 


Lançamento
Jaguaré
### Cury Cidade Jaguaré - Vila Pinheiros
2 dorms. 
Fale com um corretor
Fale com um corretor 
  * Sobre o imóvel
* * *
{ 
  * Imagens
* * *
  * Diferenciais
* * *
  * Mapa
* * *


Fale com um corretor 
  * Sobre o imóvel
* * *
  * Imagens
* * *
  * Diferenciais
* * *
  * Mapa
* * *


**Cury Cidade Jaguaré – Vila Pinheiros,** o empreendimento que vai transformar Jaguaré. Com 2 Dorms, com opção de sacada e vaga, lazer completo.
  * 1 Min. Da Marginal Pinheiros; 
  * 5 Min. Da Usp;
  * 9 Min. Do Shopping Vila Lobos e Eldorado;
  * Próximo a estação Jaguaré, Ceasa, e do parque Vila Lobos. 


**Fale agora mesmo com um corretor online e faça uma simulação.**
#### Imagens
  * Decorado
  * Foto Ilustrativa
  * Plantas
  * Vídeo tour 


  *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   * 

  *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   * 

  *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   * 

  *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   * 

  *   *   *   *   *   *   * 

  *   *   *   *   *   *   * 

Áreas comuns
#### Diferenciais
  * Piscina Adulto
  * Piscina infantil
  * Cine open air
  * Mini quadra
  * Churrasqueira
  * Salão de festas
  * Sport bar
  * Bicicletário
  * Fitness externo
  * Fitness
  * Praça de Convivência
  * Praça de acesso
  * Arejadores nas torneiras
  * Horta
  * Food square
  * Oficina
  * Easy market
  * Lavanderia
  * Playground
  * Brinquedoteca
  * Pet place
  * Pet care
  * Piso laminado nos dorms
  * Duplo acionamento nos vasos sanitários

Ver todos
Lançamento
Piscina Adulto
Piscina infantil
Cine open air
Fale com um corretor
×
#### Localização
Stand de Vendas
#### Rua Candomba, 01, Parque Continental. São Paulo - SP
Veja como chegar
Waze Google Maps
Empreendimento
#### Avenida Alexandre Mackenzie, 619, Jaguaré. São Paulo - SP
Veja como chegar
Waze Google Maps
Clique para exibir o mapa
Avenida Alexandre Mackenzie , 619 - Jaguaré 
Rua Candomba , 01 - Parque Continental 
#### Sobre a região
A **Zona Oeste de São Paulo** tem facilidade de locomoção, diversidade de comércios, instituições de ensino, e infinitas opções de lazer e cultura. Tudo isso em excelentes bairros, como: Barra Funda, Vila Madalena, Pinheiros, Sumaré, entre outros. 
O estilo de vida com facilidades, qualidade e mobilidade urbana atraem pessoas de todas as idades para morar na Zona Oeste.  

####  Imóveis relacionados 
Breve Lançamento
#### Cury Máximo Butantã
Butantã
2 Dorms, opção de terraço, suíte e lazer
Salão de Festas
Churrasqueira
Sport Bar
Quadra Gramada
Em Obras
#### Cury Flow Barra Funda 2
Barra Funda
2 Dorms, com terraço e itens compartilhados
Piscina Adulto
Piscina infantil
Easy Market
Salão de festas
Em Obras
#### Cury Flow Barra Funda
Barra Funda
2 Dorms, lazer completo e opção de terraço
Piscina Adulto
Piscina infantil
Churrasqueira
Salão de festas
Ccisa77 Incorporação Ltda. (Cidade Jaguaré – Vila Pinheiros). Incorporação Registrada Em 04/10/2021, R.3 Da Matrícula 262.959 Do 18º Oficial De Registro De Imóveis De São Paulo. Creci Sp 23670-J - Responsável Técnico Ronaldo Cury De Capua.
* * *
Utilizamos cookies essenciais e tecnologias semelhantes e, ao continuar navegando, você concorda com estas condições.
Para mais informações, confira nossa Política de Privacidade e Política de cookies
OK
##### Sobre
  * Conheça a Cury
  * Regiões
  * Área do Cliente


##### Vendas
  * Imóveis
  * Simular Financiamento
  * Fale com um Corretor


##### Comunicação
  * Contato
  * Assessoria de Imprensa
  * Relações com Investidores


##### Cury nas redes
* * *
* * *
Cury Construtora e Incorporadora S/A 2025 - CRECI 24719-J. Todos os direitos reservados. 
Confira a nossa Política de Privacidade e Política de cookies
Ok
Ofereça seu terreno 
Quero vender meu terreno em: 
São Paulo Rio de Janeiro
Envie um e-mail para adefinir@cury.net com seu **nome** , **telefone** , **área do terreno** e **localização**. 
Ou se preferir, clique aqui   
para cadastrar o seu terreno 
Assessoria de Imprensa 
E-mail: cury@maquinacohnwolfe.com 
; 
Ok
### Control your privacy
AdOpt
Our website uses cookies to improve navigation. Privacy Policy - Terms of use Developed by AdOpt
Customize Reject Accept


# Liens externes trouvés
- https://cury.gupy.io/
- http://www.relacionamentocury.com.br/
- https://api.whatsapp.com/send?phone=5521999923476&text=Olá! Tenho interesse em saber mais sobre o imóvel Cury Cidade Jaguaré - Vila Pinheiros.
- https://waze.com/ul?ll=23.54882,4675825&navigate=yes
- https://maps.google.com/maps?daddr=23.54882,4675825
- https://waze.com/ul?ll=23.53823,46.74887&navigate=yes
- https://maps.google.com/maps?daddr=23.53823,46.74887
- https://www.facebook.com/CuryConstrutora?fref=ts
- https://www.instagram.com/curyconstrutora/
- https://twitter.com/curyconstrutora
- https://www.youtube.com/user/curyconstrutora
- https://www.linkedin.com/company/cury-construtora/
- https://br.pinterest.com/curyconstrutoranet/
- https://www.tiktok.com/@curyconstrutora
- https://open.spotify.com/user/7ibqq6hybxooqerqc8ywnhqe9?si=5WTqJRxfRo6-3RoYe20vYA&nd=1
- adefinir@cury.net
- https://goadopt.io/en/porque-aviso/?utm_content=main&utm_medium=cookie_banner_web&utm_source=cookie_banner_d44972e9-1283-4d1b-b2de-6c0653a2c941
- https://hub.goadopt.io/document/2d556213-4359-44cf-a319-278f1de4e405
- https://hub.goadopt.io/document/b059c8cf-5787-49fc-9c2a-d24fd98d1b2f
  * Área do  
cliente
  * Relações com Investidores
  * Encontre sua casa própria 
São Paulo Rio de Janeiro Região Campinas  Centro  Interior  Litoral  Santo André  Zona Leste  Zona lost  Zona Norte  Zona Oeste  Zona Sul  Região Baixada Fluminense  Centro  Niterói  São Gonçalo  Zona Norte  Zona Oeste  Tipo Apartamento Casa Tipo Apartamento Casa Comercial Encontrar Encontrar


###  Selecione o que deseja: 
  * Área do Cliente
  * Conheça a Cury
  * Imóveis
  * Corretor Online
  * Imobiliárias e Corretores
  * TV Cury
  * Área do Cliente
  * Ofereça seu Terreno
  * Análise de Crédito
  * Relações com Investidores
  * Trabalhe Conosco
  * Site RJ
  * Site Campinas
  * Ouvidoria LGPD


# Oops...
## Não há nenhum conteúdo disponível nesse endereço
  * Ir para Início
  * Ver Imóveis
  * Fale com um Corretor


Utilizamos cookies e tecnologias semelhantes de acordo com a nossa Política de Privacidade e, ao continuar navegando, você concorda com estas condições.
OK X
  * Chat online
  * Simule o seu financiamento
  * Telefone:  
(11) 3230-0830 Telefone:  
(11) 3230-0830
  * Whatsapp


  * nosso facebook
  * nosso instagram
  * nosso twitter
  * nosso youtube
  * nosso linkedin
  * nosso pinterest


## Sobre
  * Conheça a Cury
  * Regiões
  * Dicas
  * TV Cury
  * Área Cliente


## Vendas
  * Imóveis
  * Simular financiamento
  * Fale com um corretor


## Comunicação
  * Contato
  * Imobiliárias e Corretores
  * Relate desvio de conduta
  * Relações com Investidores


Cury Construtora e Incorporadora S/A 2025 - CRECI 24719-J.  
Todos os direitos reservados. 
Confira a nossa  Política de Privacidade 
Ok
Fechar
Olá. Deseja receber mais informações sobre nossos empreendimentos? Deixe seus dados e entraremos em contato:
Enviar
  
com sucesso 
  
tente novamente 
Ofereça seu terreno 
Quero vender meu terreno em: 
São Paulo Rio de Janeiro
Envie um e-mail para adefinir@cury.net com seu **nome** , **telefone** , **área do terreno** e **localização**. 
Ou se preferir, clique aqui   
para cadastrar o seu terreno 


# Liens externes trouvés
- http://www.relacionamentocury.com.br/
- https://cury.gupy.io/
- https://canal.ouvidordigital.com.br/curylgpd
- tel:+55-11-3230-0830
- javascript:;
- https://api.whatsapp.com/send?phone=5521999923476&text=Olá! Tenho interesse em saber mais sobre a Cury Construtora SP
- https://www.facebook.com/CuryConstrutora?fref=ts
- https://www.instagram.com/curyconstrutora/
- https://twitter.com/curyconstrutora
- https://www.youtube.com/user/curyconstrutora
- https://www.linkedin.com/company/cury-construtora/
- https://br.pinterest.com/curyconstrutoranet/
- adefinir@cury.net
  * Imóveis 
  * Cury 
  * Serviços 
  * Área do Cliente
  * São Paulo


  * São Paulo  Rio de Janeiro 


  * Imóveis 
Cury
  * Serviços
  *   * Área do Cliente 


#### Encontre seu imóvel
Estado São Paulo Rio de Janeiro Região Campinas Centro Interior Litoral Santo André Suzano Taboão da Serra Zona Leste Zona lost Zona Norte Zona Oeste Zona Sul Zona Urbana Dormitórios Studio 1 dormitório 2 dormitórios 3 dormitórios
####  Destaques em São Paulo 
Lançamento
#### Cury Cidade Mooca
Mooca
2 dorms, opção de terraço, lazer diferenciado
Piscina Adulto
Piscina Infantil
Redário
Churrasqueira
Lançamento
#### Cury Cidade Jaguaré - Vila Pinheiros
Jaguaré
2 Dorms, lazer completo, com opção de varanda
Piscina Adulto
Piscina infantil
Cine open air
Mini quadra
Lançamento
#### Cury Mérito Vila Maria
Vila Maria
2Dorms, opção de suíte, terraço, vaga e lazer
Piscina Adulto
Piscina infantil
Churrasqueira
Salão de festas
Em breve
#### Square Panamby Itapaiuna
Panamby
Square Panamby Itapaiuna
Em breve
#### Ar.que
Vila Buarques
Teste
Piscina Adulto com Cascata
Churrasqueira
Em breve
#### Cury Square Panamby
Panamby
Cury Square Panamby
Em Obras
#### Plantão para testes 2
Casa do Will
Texto de destaque
Em Obras
#### Guedala Park Premium
Jardim Botânico
2 Dorms, lazer com piscina
Lançamento
#### Cury Cidade Mooca Vila Palermo
Mooca
2 e 3 quartos com varanda, opção de suíte e lazer completo
Piscina Adulto
Piscina infantil
Churrasqueira
Cine Open Air
Breve Lançamento
#### My Miguel Yunes
Interlagos
2 dorms, com e sem vaga e lazer integrado
Salão de festas
Churrasqueira
Quadra
Redário
Breve Lançamento
#### Cury Máximo Butantã
Butantã
2 Dorms, opção de terraço, suíte e lazer
Salão de Festas
Churrasqueira
Sport Bar
Quadra Gramada
Lançamento
#### Cury Jardim
Santo André
2 Dorms, com varanda e vaga, lazer completo
Piscina Adulto
Piscina Infantil
Salão de Festas
Food Square
Lançamento
#### Cury Cidade Mooca
Mooca
2 dorms, opção de terraço, lazer diferenciado
Piscina Adulto
Piscina Infantil
Redário
Churrasqueira
Lançamento
#### Cury Cidade Jaguaré - Vila Pinheiros
Jaguaré
2 Dorms, lazer completo, com opção de varanda
Piscina Adulto
Piscina infantil
Cine open air
Mini quadra
Lançamento
#### Cury Mérito Vila Maria
Vila Maria
2Dorms, opção de suíte, terraço, vaga e lazer
Piscina Adulto
Piscina infantil
Churrasqueira
Salão de festas
Em breve
#### Square Panamby Itapaiuna
Panamby
Square Panamby Itapaiuna
Em breve
#### Ar.que
Vila Buarques
Teste
Piscina Adulto com Cascata
Churrasqueira
Em breve
#### Cury Square Panamby
Panamby
Cury Square Panamby
Em Obras
#### Plantão para testes 2
Casa do Will
Texto de destaque
Em Obras
#### Guedala Park Premium
Jardim Botânico
2 Dorms, lazer com piscina
Lançamento
#### Cury Cidade Mooca Vila Palermo
Mooca
2 e 3 quartos com varanda, opção de suíte e lazer completo
Piscina Adulto
Piscina infantil
Churrasqueira
Cine Open Air
Breve Lançamento
#### My Miguel Yunes
Interlagos
2 dorms, com e sem vaga e lazer integrado
Salão de festas
Churrasqueira
Quadra
Redário
Breve Lançamento
#### Cury Máximo Butantã
Butantã
2 Dorms, opção de terraço, suíte e lazer
Salão de Festas
Churrasqueira
Sport Bar
Quadra Gramada
Lançamento
#### Cury Jardim
Santo André
2 Dorms, com varanda e vaga, lazer completo
Piscina Adulto
Piscina Infantil
Salão de Festas
Food Square
Lançamento
#### Cury Cidade Mooca
Mooca
2 dorms, opção de terraço, lazer diferenciado
Piscina Adulto
Piscina Infantil
Redário
Churrasqueira
Lançamento
#### Cury Cidade Jaguaré - Vila Pinheiros
Jaguaré
2 Dorms, lazer completo, com opção de varanda
Piscina Adulto
Piscina infantil
Cine open air
Mini quadra
Lançamento
#### Cury Mérito Vila Maria
Vila Maria
2Dorms, opção de suíte, terraço, vaga e lazer
Piscina Adulto
Piscina infantil
Churrasqueira
Salão de festas
  * 1
  * 2
  * 3
  * 4


####  Imóveis com a qualidade Cury 
A Cury Construtora iniciou sua história em 7 de maio de 1963 e desde o início tem o objetivo de buscar sempre melhorias e inovações constantes. 
Saiba mais 
#### Faça uma simulação
Quer uma rápida previsão de como pagar seu imóvel? Faça uma simulação:
Iniciar simulação
Utilizamos cookies essenciais e tecnologias semelhantes e, ao continuar navegando, você concorda com estas condições.
Para mais informações, confira nossa Política de Privacidade e Política de cookies
OK
##### Sobre
  * Conheça a Cury
  * Regiões
  * Área do Cliente


##### Vendas
  * Imóveis
  * Simular Financiamento
  * Fale com um Corretor


##### Comunicação
  * Contato
  * Assessoria de Imprensa
  * Relações com Investidores


##### Cury nas redes
* * *
* * *
Cury Construtora e Incorporadora S/A 2025 - CRECI 24719-J. Todos os direitos reservados. 
Confira a nossa Política de Privacidade e Política de cookies
Ok
Ofereça seu terreno 
Quero vender meu terreno em: 
São Paulo Rio de Janeiro
Envie um e-mail para adefinir@cury.net com seu **nome** , **telefone** , **área do terreno** e **localização**. 
Ou se preferir, clique aqui   
para cadastrar o seu terreno 
Assessoria de Imprensa 
E-mail: cury@maquinacohnwolfe.com 
; 
Ok
### Control your privacy
AdOpt
Our website uses cookies to improve navigation. Privacy Policy - Terms of use Developed by AdOpt
Customize Reject Accept


# Liens externes trouvés
- https://cury.gupy.io/
- http://www.relacionamentocury.com.br/
- https://api.whatsapp.com/send?phone=5521999923476&text=Olá! Tenho interesse em saber mais sobre a Cury Construtora SP
- https://www.facebook.com/CuryConstrutora?fref=ts
- https://www.instagram.com/curyconstrutora/
- https://twitter.com/curyconstrutora
- https://www.youtube.com/user/curyconstrutora
- https://www.linkedin.com/company/cury-construtora/
- https://br.pinterest.com/curyconstrutoranet/
- https://www.tiktok.com/@curyconstrutora
- https://open.spotify.com/user/7ibqq6hybxooqerqc8ywnhqe9?si=5WTqJRxfRo6-3RoYe20vYA&nd=1
- adefinir@cury.net
- https://goadopt.io/en/porque-aviso/?utm_content=main&utm_medium=cookie_banner_web&utm_source=cookie_banner_d44972e9-1283-4d1b-b2de-6c0653a2c941
- https://hub.goadopt.io/document/2d556213-4359-44cf-a319-278f1de4e405
- https://hub.goadopt.io/document/b059c8cf-5787-49fc-9c2a-d24fd98d1b2f
  * Imóveis 
  * Cury 
  * Serviços 
  * Área do Cliente
  * São Paulo


  * São Paulo  Rio de Janeiro 


  * Imóveis 
Cury
  * Serviços
  *   * Área do Cliente 


Voltar
## Imobiliárias e Corretoras
Bem-vindo à plataforma de parcerias da Cury Construtora.  

### Quero ser uma Imobiliária Parceira
Para se tornar uma imobiliária parceira, entre em contato conosco através do e-mail rhcuryvendas@cury.net.
### Quero ser um Corretor
Se você deseja ser um corretor parceiro Cury, baixe o nosso app na loja respectiva do seu smartphone e faça o seu cadastro.
Utilizamos cookies essenciais e tecnologias semelhantes e, ao continuar navegando, você concorda com estas condições.
Para mais informações, confira nossa Política de Privacidade e Política de cookies
OK
##### Sobre
  * Conheça a Cury
  * Regiões
  * Área do Cliente


##### Vendas
  * Imóveis
  * Simular Financiamento
  * Fale com um Corretor


##### Comunicação
  * Contato
  * Assessoria de Imprensa
  * Relações com Investidores


##### Cury nas redes
* * *
* * *
Cury Construtora e Incorporadora S/A 2025 - CRECI 24719-J. Todos os direitos reservados. 
Confira a nossa Política de Privacidade e Política de cookies
Ok
Ofereça seu terreno 
Quero vender meu terreno em: 
São Paulo Rio de Janeiro
Envie um e-mail para adefinir@cury.net com seu **nome** , **telefone** , **área do terreno** e **localização**. 
Ou se preferir, clique aqui   
para cadastrar o seu terreno 
Assessoria de Imprensa 
E-mail: cury@maquinacohnwolfe.com 
; 
Ok
### Control your privacy
AdOpt
Our website uses cookies to improve navigation. Privacy Policy - Terms of use Developed by AdOpt
Customize Reject Accept


# Liens externes trouvés
- https://cury.gupy.io/
- http://www.relacionamentocury.com.br/
- https://api.whatsapp.com/send?phone=5521999923476&text=Olá! Tenho interesse em saber mais sobre a Cury Construtora SP
- javascript:history.back();
- rhcuryvendas@cury.net
- https://play.google.com/store/apps/details?id=com.cury&pli=1
- https://apps.apple.com/br/app/cury-corretor/id1547639146
- https://www.facebook.com/CuryConstrutora?fref=ts
- https://www.instagram.com/curyconstrutora/
- https://twitter.com/curyconstrutora
- https://www.youtube.com/user/curyconstrutora
- https://www.linkedin.com/company/cury-construtora/
- https://br.pinterest.com/curyconstrutoranet/
- https://www.tiktok.com/@curyconstrutora
- https://open.spotify.com/user/7ibqq6hybxooqerqc8ywnhqe9?si=5WTqJRxfRo6-3RoYe20vYA&nd=1
- adefinir@cury.net
- https://goadopt.io/en/porque-aviso/?utm_content=main&utm_medium=cookie_banner_web&utm_source=cookie_banner_d44972e9-1283-4d1b-b2de-6c0653a2c941
- https://hub.goadopt.io/document/2d556213-4359-44cf-a319-278f1de4e405
- https://hub.goadopt.io/document/b059c8cf-5787-49fc-9c2a-d24fd98d1b2f
  * Imóveis 
  * Cury 
  * Serviços 
  * Área do Cliente
  * São Paulo


  * São Paulo  Rio de Janeiro 


  * Imóveis 
Cury
  * Serviços
  *   * Área do Cliente 


Voltar
## Análise de crédito
A aprovação do crédito é muito importante, por isso criamos um processo seguro e 100% online. Você só precisa fazer seu cadastro e enviar os documentos necessários. No final, você pode fazer a assinatura eletrônica do seu contrato. Tudo sem sair de casa! 
Lista de documentos
#### Já possuo os documentos
Já está com os documentos? Então vamos começar
Começar
#### Processo em andamento
Você tem um processo em andamento? Digite seu e-mail para continuar.
Continuar
#### Corretores Cury
Você é um corretor Cury?
Continuar
×
#### Documentos necessários
**As informações destes documentos são confidenciais, e nossa equipe as usa para concluir a sua análise de crédito. É 100% seguro, pode confiar.**
  * **RG/CPF (frente e verso), RG Funcional ou CNH** - Documento dentro da validade 
  * **Certidão de Estado Civil** - Nascimento, Casamento ou Casamento + Óbito ou Certidão averbada contendo divorcio/separação 
  * **Comprovante de Endereço** - Água, luz, telefone, extratos bancários, fatura de cartão de crédito - com validade de até 60 dias 
  * **Comprovante de Renda:**   

**_Formal_** - 02 Últimos Holerites atualizados, em caso de empregada doméstica, os 2 últimos E-Social   
**_Informal_** - caso possua - 06 últimos extratos conta-corrente com Limite de cheque especial - conta-pessoa fisica   
**_Aposentados e Pensionistas_** - 02 últimos históricos de pagamento mais Carta de Concessão ou Extrato de pagamento do INSS 
  * **Carteira de Trabalho** - Página da foto, qualificação civil, contratos de trabalho e anotações gerais 
  * **FGTS** - Retirado da Caixa, emitido pela internet ou extrato analítico (contendo todas informações) 
  * **Imposto de Renda + Protocolo de entrega** - Enviar versão completa. Caso tenha retificado, apresentar todas as retificações juntamente com a declaração original. 


Enviamos um e-mail para o endereço **xxxxxxxx@xxxxxx.com**.   
Favor clicar no link enviado para dar continuidade ao processo de análise de crédito.
**URL de login inválida.**  
  
Digite seu e-mail novamente  
para continuar. 
Utilizamos cookies essenciais e tecnologias semelhantes e, ao continuar navegando, você concorda com estas condições.
Para mais informações, confira nossa Política de Privacidade e Política de cookies
OK
##### Sobre
  * Conheça a Cury
  * Regiões
  * Área do Cliente


##### Vendas
  * Imóveis
  * Simular Financiamento
  * Fale com um Corretor


##### Comunicação
  * Contato
  * Assessoria de Imprensa
  * Relações com Investidores


##### Cury nas redes
* * *
* * *
Cury Construtora e Incorporadora S/A 2025 - CRECI 24719-J. Todos os direitos reservados. 
Confira a nossa Política de Privacidade e Política de cookies
Ok
Ofereça seu terreno 
Quero vender meu terreno em: 
São Paulo Rio de Janeiro
Envie um e-mail para adefinir@cury.net com seu **nome** , **telefone** , **área do terreno** e **localização**. 
Ou se preferir, clique aqui   
para cadastrar o seu terreno 
Assessoria de Imprensa 
E-mail: cury@maquinacohnwolfe.com 
; 
Ok
### Control your privacy
AdOpt
Our website uses cookies to improve navigation. Privacy Policy - Terms of use Developed by AdOpt
Customize Reject Accept


# Liens externes trouvés
- https://cury.gupy.io/
- http://www.relacionamentocury.com.br/
- https://api.whatsapp.com/send?phone=5521999923476&text=Olá! Tenho interesse em saber mais sobre a Cury Construtora SP
- javascript:history.back();
- https://www.facebook.com/CuryConstrutora?fref=ts
- https://www.instagram.com/curyconstrutora/
- https://twitter.com/curyconstrutora
- https://www.youtube.com/user/curyconstrutora
- https://www.linkedin.com/company/cury-construtora/
- https://br.pinterest.com/curyconstrutoranet/
- https://www.tiktok.com/@curyconstrutora
- https://open.spotify.com/user/7ibqq6hybxooqerqc8ywnhqe9?si=5WTqJRxfRo6-3RoYe20vYA&nd=1
- adefinir@cury.net
- https://goadopt.io/en/porque-aviso/?utm_content=main&utm_medium=cookie_banner_web&utm_source=cookie_banner_d44972e9-1283-4d1b-b2de-6c0653a2c941
- https://hub.goadopt.io/document/2d556213-4359-44cf-a319-278f1de4e405
- https://hub.goadopt.io/document/b059c8cf-5787-49fc-9c2a-d24fd98d1b2f
  * Imóveis 
  * Cury 
  * Serviços 
  * Área do Cliente
  * São Paulo


  * São Paulo  Rio de Janeiro 


  * Imóveis 
Cury
  * Serviços
  *   * Área do Cliente 


Esta Política de Cookies (“Política”) aplica-se ao site Cury (https://cury.net) (“Plataforma”), da Cury Construtora e Incorporadora S.A., pessoa jurídica de direito privado, devidamente inscrita no CNPJ sob o nº CNPJ/MF sob o nº 08.797.760/0001-83, estabelecida na Rua Funchal, nº 411, 13º andar, no município de São Paulo, estado de São Paulo isoladamente ou em conjunto com suas Sociedades de Propósito Específico e/ou as demais empresas que integram seu grupo econômico (“Nós”).
  

## 1 - INTRODUÇÃO
Temos a intenção de proporcionar a você, que acessa e utiliza nossa Plataforma (“Usuário”) uma experiência ainda mais transparente, explicando o conceito de cookies, como os utilizamos e, ainda, as possibilidades de customização do seu uso.
Caso não concorde com o uso de cookies da forma apresentada, o Usuário poderá se recusar a aceitá-los, não clicando em “OK” no aviso que salta à sua tela quando acessa nossa plataforma, ajustar as configurações do navegador que utiliza para não permitir o uso de cookies ou não acessar a Plataforma.
Importante mencionar que a desabilitação do uso de cookies poderá impactar a experiência do Usuário ao utilizar a nossa Plataforma.
Recomendamos também a leitura da nossa Política de Privacidade, na qual trazemos mais informações sobre nosso compromisso com a privacidade do Usuário e a proteção dos seus dados pessoais.
Para quaisquer questões ou dúvidas sobre esta Política, o Usuário poderá entrar em contato com o Encarregado da Cury pelo site https://canal.ouvidordigital.com.br/curylgpd.
  

## 2 - O QUE SÃO COOKIES
Cookies são pequenos arquivos digitais em formato de texto que são armazenados no dispositivo eletrônico do Usuário quando ele acessa nossa Plataforma. Os cookies guardam informações relacionadas às suas preferências, como idioma preferido, localização, recorrência das suas sessões e outras variáveis que os desenvolvedores da Plataforma consideram relevantes para tornar a sua experiência muito mais eficiente.
  

## 3 - PARA QUE SERVEM OS COOKIES
Os cookies servem para aprimorar a experiência do Usuário em nossa Plataforma, tanto em termos de performance, como em termos de usabilidade, uma vez que os conteúdos disponibilizados serão direcionados às suas necessidades e expectativas.
Eles também podem ser utilizados para realizar estatísticas anônimas que permitem entender como os Usuários utilizam a Plataforma, bem como para aprimorar suas estruturas e conteúdo. Por serem estatísticas anônimas, não é possível identificá-lo pessoalmente por meio desses dados.
  

## 4 - COOKIES UTILIZADOS NA PLATAFORMA
Nós utilizamos dois tipos de cookies na nossa Plataforma:
Cookies de Sessão: são os cookies temporários que permanecem arquivados até que o Usuário saia da Plataforma ou encerre o navegador.
Cookies Persistentes: são os cookies que ficam armazenados no dispositivo do Usuário até que sejam excluídos (o tempo que o Cookie permanecerá no dispositivo depende de sua "validade" e das configurações do seu navegador de internet). São esses cookies que são utilizados no acesso à Plataforma, mostrando os conteúdos mais relevantes e personalizados de acordo com os interesses do Usuário.
Os cookies (de Sessão ou Persistentes) podem ser categorizados de acordo com sua função:
Cookies Estritamente Necessários: permitem a navegação e utilização das aplicações, bem como acessar a áreas seguras da Plataforma. Sem estes cookies, a Plataforma não funciona corretamente.
Cookies Analíticos: coletam dados estatísticos anônimos com a finalidade de analisar a utilização da Plataforma e seu respectivo desempenho. Esse tipo de cookies é essencial para mantermos uma performance positiva, como: entender quais são as páginas mais populares e verificar o motivo dos erros apresentados nas páginas. Esses cookies não coletam nenhum dado pessoal.
  

Cookies de Funcionalidade: são utilizados para assegurar a disponibilização de funcionalidades adicionais da Plataforma ou para guardar as preferências definidas pelo Usuário ao navegar na internet, sempre que utilizar o mesmo dispositivo.
Cookies de Publicidade: coletam as informações de visita em nossa Plataforma para que as propagandas nela dispostas sejam mais relevantes para o Usuário e de acordo com os seus interesses. Geralmente estão atrelados a cookies de propriedade de terceiros. Caso você desabilite estes cookies, note que ainda visualizará as publicidades, mas elas serão personalizadas às suas preferências.
  

## 5 - COMO CONTROLAR OU ELIMINAR COOKIES
A maioria dos navegadores é configurada para aceitar automaticamente os cookies.
O Usuário pode alterar as configurações para bloquear o seu uso ou alertá-lo quando um
cookie estiver sendo enviado para seu dispositivo eletrônico.
Existem várias formas de gerenciar cookies. Consulte as instruções ou a seção de ajuda, tools ou edit, do seu navegador para saber mais sobre como ajustar ou alterar essas configurações.
Disponibilizamos abaixo alguns links para os navegadores mais conhecidos:
Firefox
Chrome
Internet Explorer
Safari
Opera
Microsoft Edge
  

  

Fechar
asdasd dasdsadsa asddsadsa asdadsdas saddasdsaasd
Aceito receber contato por telefone
Aceito receber contato por SMS
Aceito receber contato por WhatsApp
Aceito receber contato por e-mail
Caso o download não seja iniciado automaticamente, clique aqui para baixar o arquivo.
Utilizamos cookies essenciais e tecnologias semelhantes e, ao continuar navegando, você concorda com estas condições.
Para mais informações, confira nossa Política de Privacidade e Política de cookies
OK
##### Sobre
  * Conheça a Cury
  * Regiões
  * Área do Cliente


##### Vendas
  * Imóveis
  * Simular Financiamento
  * Fale com um Corretor


##### Comunicação
  * Contato
  * Assessoria de Imprensa
  * Relações com Investidores


##### Cury nas redes
* * *
* * *
Cury Construtora e Incorporadora S/A 2025 - CRECI 24719-J. Todos os direitos reservados. 
Confira a nossa Política de Privacidade e Política de cookies
Ok
Ofereça seu terreno 
Quero vender meu terreno em: 
São Paulo Rio de Janeiro
Envie um e-mail para adefinir@cury.net com seu **nome** , **telefone** , **área do terreno** e **localização**. 
Ou se preferir, clique aqui   
para cadastrar o seu terreno 
Assessoria de Imprensa 
E-mail: cury@maquinacohnwolfe.com 
; 
Ok
### Control your privacy
AdOpt
Our website uses cookies to improve navigation. Privacy Policy - Terms of use Developed by AdOpt
Customize Reject Accept


# Liens externes trouvés
- https://cury.gupy.io/
- http://www.relacionamentocury.com.br/
- https://api.whatsapp.com/send?phone=5521999923476&text=Olá! Tenho interesse em saber mais sobre a Cury Construtora SP
- https://www.facebook.com/CuryConstrutora?fref=ts
- https://www.instagram.com/curyconstrutora/
- https://twitter.com/curyconstrutora
- https://www.youtube.com/user/curyconstrutora
- https://www.linkedin.com/company/cury-construtora/
- https://br.pinterest.com/curyconstrutoranet/
- https://www.tiktok.com/@curyconstrutora
- https://open.spotify.com/user/7ibqq6hybxooqerqc8ywnhqe9?si=5WTqJRxfRo6-3RoYe20vYA&nd=1
- adefinir@cury.net
- https://goadopt.io/en/porque-aviso/?utm_content=main&utm_medium=cookie_banner_web&utm_source=cookie_banner_d44972e9-1283-4d1b-b2de-6c0653a2c941
- https://hub.goadopt.io/document/2d556213-4359-44cf-a319-278f1de4e405
- https://hub.goadopt.io/document/b059c8cf-5787-49fc-9c2a-d24fd98d1b2f
  * Imóveis 
  * Cury 
  * Serviços 
  * Área do Cliente
  * São Paulo


  * São Paulo  Rio de Janeiro 


  * Imóveis 
Cury
  * Serviços
  *   * Área do Cliente 


Voltar
#### Imóveis em São Paulo
Estado e Região
0
##### Estado
São Paulo  Rio de Janeiro 
##### Regiões
Campinas  Centro  Interior  Litoral  Santo André  Zona Leste  Zona lost  Zona Norte  Zona Oeste  Zona Sul 
Baixada Fluminense  Centro  Niterói  São Gonçalo  Zona Norte  Zona Oeste 
Filtrar
Estágio da obra
0
##### Estágio da obra
Em breve  Breve Lançamento  Lançamento  Em Obras  Pronto para Morar 
Em breve  Lançamento  Em Obras  Pronto para Morar 
Filtrar
Dormitórios
0
##### Dormitórios
Studio  1 dormitório  2 dormitórios  3 dormitórios 
Studio  1 dormitório  2 dormitórios  3 dormitórios 
Filtrar
Tipo de imóvel
0
##### Tipo de imóvel
Apartamento  Casa 
Apartamento  Casa  Comercial 
Filtrar
Valor do imóvel
##### Valor do imóvel
De 100 até 600
100 mil
600 mil
Filtrar
Em breve
#### Square Panamby Itapaiuna
Panamby
Square Panamby Itapaiuna
Em breve
#### Ar.que
Vila Buarques
Teste
Piscina Adulto com Cascata
Churrasqueira
Em breve
#### Cury Square Panamby
Panamby
Cury Square Panamby
Em Obras
#### Plantão para testes 2
Casa do Will
Texto de destaque
Em Obras
#### Guedala Park Premium
Jardim Botânico
2 Dorms, lazer com piscina
Lançamento
#### Cury Cidade Mooca Vila Palermo
Mooca
2 e 3 quartos com varanda, opção de suíte e lazer completo
Piscina Adulto
Piscina infantil
Churrasqueira
Cine Open Air
Quadra Gramada
Espaço Games
Breve Lançamento
#### My Miguel Yunes
Interlagos
2 dorms, com e sem vaga e lazer integrado
Salão de festas
Churrasqueira
Quadra
Redário
Cinema
Praça do Fogo
Breve Lançamento
#### Cury Máximo Butantã
Butantã
2 Dorms, opção de terraço, suíte e lazer
Salão de Festas
Churrasqueira
Sport Bar
Quadra Gramada
Food Square
Cine Open Air
Lançamento
#### Cury Jardim
Santo André
2 Dorms, com varanda e vaga, lazer completo
Piscina Adulto
Piscina Infantil
Salão de Festas
Food Square
Cine Open Air
Bar Praia
Lançamento
#### Cury Cidade Mooca
Mooca
2 dorms, opção de terraço, lazer diferenciado
Piscina Adulto
Piscina Infantil
Redário
Churrasqueira
Sala de Descanso com Sauna
Home Office
Lançamento
#### Cury Cidade Jaguaré - Vila Pinheiros
Jaguaré
2 Dorms, lazer completo, com opção de varanda
Piscina Adulto
Piscina infantil
Cine open air
Mini quadra
Churrasqueira
Salão de festas
Lançamento
#### Cury Mérito Vila Maria
Vila Maria
2Dorms, opção de suíte, terraço, vaga e lazer
Piscina Adulto
Piscina infantil
Churrasqueira
Salão de festas
Bar
Sala de descanso com sauna
1 2 3 4 5 6 7 8
Utilizamos cookies essenciais e tecnologias semelhantes e, ao continuar navegando, você concorda com estas condições.
Para mais informações, confira nossa Política de Privacidade e Política de cookies
OK
##### Sobre
  * Conheça a Cury
  * Regiões
  * Área do Cliente


##### Vendas
  * Imóveis
  * Simular Financiamento
  * Fale com um Corretor


##### Comunicação
  * Contato
  * Assessoria de Imprensa
  * Relações com Investidores


##### Cury nas redes
* * *
* * *
Cury Construtora e Incorporadora S/A 2025 - CRECI 24719-J. Todos os direitos reservados. 
Confira a nossa Política de Privacidade e Política de cookies
Ok
Ofereça seu terreno 
Quero vender meu terreno em: 
São Paulo Rio de Janeiro
Envie um e-mail para adefinir@cury.net com seu **nome** , **telefone** , **área do terreno** e **localização**. 
Ou se preferir, clique aqui   
para cadastrar o seu terreno 
Assessoria de Imprensa 
E-mail: cury@maquinacohnwolfe.com 
; 
Ok
### Control your privacy
AdOpt
Our website uses cookies to improve navigation. Privacy Policy - Terms of use Developed by AdOpt
Customize Reject Accept


# Liens externes trouvés
- https://cury.gupy.io/
- http://www.relacionamentocury.com.br/
- https://api.whatsapp.com/send?phone=5521999923476&text=Olá! Tenho interesse em saber mais sobre a Cury Construtora SP
- https://www.facebook.com/CuryConstrutora?fref=ts
- https://www.instagram.com/curyconstrutora/
- https://twitter.com/curyconstrutora
- https://www.youtube.com/user/curyconstrutora
- https://www.linkedin.com/company/cury-construtora/
- https://br.pinterest.com/curyconstrutoranet/
- https://www.tiktok.com/@curyconstrutora
- https://open.spotify.com/user/7ibqq6hybxooqerqc8ywnhqe9?si=5WTqJRxfRo6-3RoYe20vYA&nd=1
- adefinir@cury.net
- https://goadopt.io/en/porque-aviso/?utm_content=main&utm_medium=cookie_banner_web&utm_source=cookie_banner_d44972e9-1283-4d1b-b2de-6c0653a2c941
- https://hub.goadopt.io/document/2d556213-4359-44cf-a319-278f1de4e405
- https://hub.goadopt.io/document/b059c8cf-5787-49fc-9c2a-d24fd98d1b2f
  * Imóveis 
  * Cury 
  * Serviços 
  * Área do Cliente
  * São Paulo


  * São Paulo  Rio de Janeiro 


  * Imóveis 
Cury
  * Serviços
  *   * Área do Cliente 


A inovação está no DNA da Cury Construtora. Ao longo de sua história, a empresa sempre buscou soluções ousadas e modernas para entregar empreendimentos que elevassem o padrão da construção civil no país.
Agora, a Cury dá mais um passo nesta jornada e lança o Inova Cury, uma plataforma inédita para impulsionar a inovação aberta e colaborativa. Este hub conecta a Cury a um amplo ecossistema de startups, universidades, fornecedores e parceiros, que terão a oportunidade de propor soluções inovadoras para os desafios da construção.
Por meio do Inova Cury, a Cury convida você a participar ativamente na construção do futuro da companhia e da sociedade. Temos o privilégio de contar com mentes brilhantes, capazes de criar tecnologias exponenciais com impacto tangível na vida das pessoas. As portas estão abertas para receber seus projetos e ideias.
Junte-se a nós nesta empolgante jornada. O Inova Cury existe para impulsionar seu potencial transformador, trazendo inovações que revolucionem a experiência de morar das pessoas. Vamos juntos elevar a inovação na Cury a novos patamares.
####  Desafios em andamento 
Tecnologia
#### Moradias Populares do Futuro Sustentável e Acessível
Título do Desafio: Inovando a Habitação
Inscrições até: 31/10/2023
Saiba mais
Tecnologia
#### Desenvolver uma nova forma de medir a estrutura dos terrenos
Revolucionando a Medição Estrutural de Terrenos
Inscrições até: 12/12/2024
Saiba mais
Tecnologia
#### Acelerar o processo de terraplanagem, porém sem agredir o meio ambiente e com o menor custo possível.
Terraplanagem Rápida e Sustentável:
Inscrições até: 01/01/2025
Saiba mais
Tecnologia
#### Acelerar o processo de terraplanagem, porém sem agredir o meio ambiente e com o menor custo possível.
"Desafio de Inovação: Acelerando a Terraplanagem com Eficiência, Economia e Sustentabilidade"
Inscrições até: 12/10/2023
Saiba mais
Tecnologia
#### Acelerar o processo de terraplanagem, porém sem agredir o meio ambiente e com o menor custo possível.
"Desafio de Inovação para Aceleração Sustentável e Econômica do Processo de Terraplanagem"
Inscrições até: 12/10/2023
Saiba mais
Tecnologia
#### Acelerar o processo de inovação tecnológica
"Desafio: Acelerando a Inovação Tecnológica para um Futuro Mais Eficiente"
Inscrições até: 15/12/2024
Saiba mais
Tecnologia
#### Acelerar o processo de terraplanagem, porém sem agredir o meio ambiente e com o menor custo possível.
Terraplanagem Sustentável: Inovação e Economia
Inscrições até: 12/12/2026
Saiba mais
Digital
#### Conseguir mensurar os dados de leads x vendas para encontrar o ROI, mas usar algo escalável por hierarquia pois os dados devem ser separados por equipes de vendas e será usado em um aplicativ
Desafio: ROI Hierarquizado e Escalável
Inscrições até: 26/10/2023
Saiba mais
Tecnologia
#### Moradias Populares do Futuro Sustentável e Acessível
Título do Desafio: Inovando a Habitação
Inscrições até: 31/10/2023
Saiba mais
Tecnologia
#### Desenvolver uma nova forma de medir a estrutura dos terrenos
Revolucionando a Medição Estrutural de Terrenos
Inscrições até: 12/12/2024
Saiba mais
Tecnologia
#### Acelerar o processo de terraplanagem, porém sem agredir o meio ambiente e com o menor custo possível.
Terraplanagem Rápida e Sustentável:
Inscrições até: 01/01/2025
Saiba mais
Tecnologia
#### Acelerar o processo de terraplanagem, porém sem agredir o meio ambiente e com o menor custo possível.
"Desafio de Inovação: Acelerando a Terraplanagem com Eficiência, Economia e Sustentabilidade"
Inscrições até: 12/10/2023
Saiba mais
Tecnologia
#### Acelerar o processo de terraplanagem, porém sem agredir o meio ambiente e com o menor custo possível.
"Desafio de Inovação para Aceleração Sustentável e Econômica do Processo de Terraplanagem"
Inscrições até: 12/10/2023
Saiba mais
Tecnologia
#### Acelerar o processo de inovação tecnológica
"Desafio: Acelerando a Inovação Tecnológica para um Futuro Mais Eficiente"
Inscrições até: 15/12/2024
Saiba mais
Tecnologia
#### Acelerar o processo de terraplanagem, porém sem agredir o meio ambiente e com o menor custo possível.
Terraplanagem Sustentável: Inovação e Economia
Inscrições até: 12/12/2026
Saiba mais
Digital
#### Conseguir mensurar os dados de leads x vendas para encontrar o ROI, mas usar algo escalável por hierarquia pois os dados devem ser separados por equipes de vendas e será usado em um aplicativ
Desafio: ROI Hierarquizado e Escalável
Inscrições até: 26/10/2023
Saiba mais
Tecnologia
#### Moradias Populares do Futuro Sustentável e Acessível
Título do Desafio: Inovando a Habitação
Inscrições até: 31/10/2023
Saiba mais
Tecnologia
#### Desenvolver uma nova forma de medir a estrutura dos terrenos
Revolucionando a Medição Estrutural de Terrenos
Inscrições até: 12/12/2024
Saiba mais
Tecnologia
#### Acelerar o processo de terraplanagem, porém sem agredir o meio ambiente e com o menor custo possível.
Terraplanagem Rápida e Sustentável:
Inscrições até: 01/01/2025
Saiba mais
  * 1
  * 2
  * 3


### Seja um parceiro  
de inovação
Faça o cadastro e nos conte como sua organização pode ser nossa parceira de inovação.
Cadastre-se
###### ICON HUB
O iCON Hub é o programa de inovação aberta do SindusCon-SP, realizado em parceria com a Neoventures, para que as empresas da cadeia da construção encontrem apoio em sua jornada de inovação. 
Foi criado em 2020 para fomentar um ecossistema de inovação na construção civil por meio de conexão com startups, capacitação de embaixadores de inovação e eventos exclusivos.
###### Fique antenado
Quer saber tudo sobre o Inova Cury?   
Assine nossa Newsletter
Li e estou de acordo com os Termos de Uso e Política de Privacidade
Inscrever-me
Utilizamos cookies essenciais e tecnologias semelhantes e, ao continuar navegando, você concorda com estas condições.
Para mais informações, confira nossa Política de Privacidade e Política de cookies
OK
##### Sobre
  * Conheça a Cury
  * Regiões
  * Área do Cliente


##### Vendas
  * Imóveis
  * Simular Financiamento
  * Fale com um Corretor


##### Comunicação
  * Contato
  * Assessoria de Imprensa
  * Relações com Investidores


##### Cury nas redes
* * *
* * *
Cury Construtora e Incorporadora S/A 2025 - CRECI 24719-J. Todos os direitos reservados. 
Confira a nossa Política de Privacidade e Política de cookies
Ok
Ofereça seu terreno 
Quero vender meu terreno em: 
São Paulo Rio de Janeiro
Envie um e-mail para adefinir@cury.net com seu **nome** , **telefone** , **área do terreno** e **localização**. 
Ou se preferir, clique aqui   
para cadastrar o seu terreno 
Assessoria de Imprensa 
E-mail: cury@maquinacohnwolfe.com 
; 
Ok
### Control your privacy
AdOpt
Our website uses cookies to improve navigation. Privacy Policy - Terms of use Developed by AdOpt
Customize Reject Accept


# Liens externes trouvés
- https://cury.gupy.io/
- http://www.relacionamentocury.com.br/
- https://api.whatsapp.com/send?phone=5521999923476&text=Olá! Tenho interesse em saber mais sobre a Cury Construtora SP
- https://www.facebook.com/CuryConstrutora?fref=ts
- https://www.instagram.com/curyconstrutora/
- https://twitter.com/curyconstrutora
- https://www.youtube.com/user/curyconstrutora
- https://www.linkedin.com/company/cury-construtora/
- https://br.pinterest.com/curyconstrutoranet/
- https://www.tiktok.com/@curyconstrutora
- https://open.spotify.com/user/7ibqq6hybxooqerqc8ywnhqe9?si=5WTqJRxfRo6-3RoYe20vYA&nd=1
- adefinir@cury.net
- https://goadopt.io/en/porque-aviso/?utm_content=main&utm_medium=cookie_banner_web&utm_source=cookie_banner_d44972e9-1283-4d1b-b2de-6c0653a2c941
- https://hub.goadopt.io/document/2d556213-4359-44cf-a319-278f1de4e405
- https://hub.goadopt.io/document/b059c8cf-5787-49fc-9c2a-d24fd98d1b2f
  * Imóveis 
  * Cury 
  * Serviços 
  * Área do Cliente
  * São Paulo


  * São Paulo  Rio de Janeiro 


  * Imóveis 
Cury
  * Serviços
  *   * Área do Cliente 


Lançamento
Jaguaré
### Cury Cidade Jaguaré - Vila Pinheiros
2 dorms. 
Fale com um corretor
Fale com um corretor 
  * Sobre o imóvel
* * *
{ 
  * Imagens
* * *
  * Diferenciais
* * *
  * Mapa
* * *


Fale com um corretor 
  * Sobre o imóvel
* * *
  * Imagens
* * *
  * Diferenciais
* * *
  * Mapa
* * *


**Cury Cidade Jaguaré – Vila Pinheiros,** o empreendimento que vai transformar Jaguaré. Com 2 Dorms, com opção de sacada e vaga, lazer completo.
  * 1 Min. Da Marginal Pinheiros; 
  * 5 Min. Da Usp;
  * 9 Min. Do Shopping Vila Lobos e Eldorado;
  * Próximo a estação Jaguaré, Ceasa, e do parque Vila Lobos. 


**Fale agora mesmo com um corretor online e faça uma simulação.**
#### Imagens
  * Decorado
  * Foto Ilustrativa
  * Plantas
  * Vídeo tour 


  *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   * 

  *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   * 

  *   *   *   *   *   *   * 

Áreas comuns
#### Diferenciais
  * Piscina Adulto
  * Piscina infantil
  * Cine open air
  * Mini quadra
  * Churrasqueira
  * Salão de festas
  * Sport bar
  * Bicicletário
  * Fitness externo
  * Fitness
  * Praça de Convivência
  * Praça de acesso
  * Arejadores nas torneiras
  * Horta
  * Food square
  * Oficina
  * Easy market
  * Lavanderia
  * Playground
  * Brinquedoteca
  * Pet place
  * Pet care
  * Piso laminado nos dorms
  * Duplo acionamento nos vasos sanitários

Ver todos
Lançamento
Piscina Adulto
Piscina infantil
Cine open air
Fale com um corretor
×
#### Localização
Stand de Vendas
#### Rua Candomba, 01, Parque Continental. São Paulo - SP
Veja como chegar
Waze Google Maps
Empreendimento
#### Avenida Alexandre Mackenzie, 619, Jaguaré. São Paulo - SP
Veja como chegar
Waze Google Maps
Clique para exibir o mapa
Avenida Alexandre Mackenzie , 619 - Jaguaré 
Rua Candomba , 01 - Parque Continental 
#### Sobre a região
A **Zona Oeste de São Paulo** tem facilidade de locomoção, diversidade de comércios, instituições de ensino, e infinitas opções de lazer e cultura. Tudo isso em excelentes bairros, como: Barra Funda, Vila Madalena, Pinheiros, Sumaré, entre outros. 
O estilo de vida com facilidades, qualidade e mobilidade urbana atraem pessoas de todas as idades para morar na Zona Oeste.  

####  Imóveis relacionados 
Breve Lançamento
#### Cury Máximo Butantã
Butantã
2 Dorms, opção de terraço, suíte e lazer
Salão de Festas
Churrasqueira
Sport Bar
Quadra Gramada
Em Obras
#### Cury Flow Barra Funda 2
Barra Funda
2 Dorms, com terraço e itens compartilhados
Piscina Adulto
Piscina infantil
Easy Market
Salão de festas
Em Obras
#### Cury Flow Barra Funda
Barra Funda
2 Dorms, lazer completo e opção de terraço
Piscina Adulto
Piscina infantil
Churrasqueira
Salão de festas
Ccisa77 Incorporação Ltda. (Cidade Jaguaré – Vila Pinheiros). Incorporação Registrada Em 04/10/2021, R.3 Da Matrícula 262.959 Do 18º Oficial De Registro De Imóveis De São Paulo. Creci Sp 23670-J - Responsável Técnico Ronaldo Cury De Capua.
* * *
Utilizamos cookies essenciais e tecnologias semelhantes e, ao continuar navegando, você concorda com estas condições.
Para mais informações, confira nossa Política de Privacidade e Política de cookies
OK
##### Sobre
  * Conheça a Cury
  * Regiões
  * Área do Cliente


##### Vendas
  * Imóveis
  * Simular Financiamento
  * Fale com um Corretor


##### Comunicação
  * Contato
  * Assessoria de Imprensa
  * Relações com Investidores


##### Cury nas redes
* * *
* * *
Cury Construtora e Incorporadora S/A 2025 - CRECI 24719-J. Todos os direitos reservados. 
Confira a nossa Política de Privacidade e Política de cookies
Ok
Ofereça seu terreno 
Quero vender meu terreno em: 
São Paulo Rio de Janeiro
Envie um e-mail para adefinir@cury.net com seu **nome** , **telefone** , **área do terreno** e **localização**. 
Ou se preferir, clique aqui   
para cadastrar o seu terreno 
Assessoria de Imprensa 
E-mail: cury@maquinacohnwolfe.com 
; 
Ok


# Liens externes trouvés
- https://cury.gupy.io/
- http://www.relacionamentocury.com.br/
- https://api.whatsapp.com/send?phone=5521999923476&text=Olá! Tenho interesse em saber mais sobre o imóvel Cury Cidade Jaguaré - Vila Pinheiros.
- https://waze.com/ul?ll=23.54882,4675825&navigate=yes
- https://maps.google.com/maps?daddr=23.54882,4675825
- https://waze.com/ul?ll=23.53823,46.74887&navigate=yes
- https://maps.google.com/maps?daddr=23.53823,46.74887
- https://www.facebook.com/CuryConstrutora?fref=ts
- https://www.instagram.com/curyconstrutora/
- https://twitter.com/curyconstrutora
- https://www.youtube.com/user/curyconstrutora
- https://www.linkedin.com/company/cury-construtora/
- https://br.pinterest.com/curyconstrutoranet/
- https://www.tiktok.com/@curyconstrutora
- https://open.spotify.com/user/7ibqq6hybxooqerqc8ywnhqe9?si=5WTqJRxfRo6-3RoYe20vYA&nd=1
- adefinir@cury.net
  * Imóveis 
  * Cury 
  * Serviços 
  * Área do Cliente
  * São Paulo


  * São Paulo  Rio de Janeiro 


  * Imóveis 
Cury
  * Serviços
  *   * Área do Cliente 


Em Obras
Barra Funda
### Cury Flow Barra Funda 2
2 dorms. 
Fale com um corretor
Fale com um corretor 
  * Sobre o imóvel
* * *
{ 
  * Imagens
* * *
  * Diferenciais
* * *
  * Mapa
* * *
  * Obras
* * *


Fale com um corretor 
  * Sobre o imóvel
* * *
  * Imagens
* * *
  * Diferenciais
* * *
  * Mapa
* * *
  * Obras
* * *


Viva a cada momento dentro do **Flow Barra Funda 2!** Mobilidade para quem vai, conforto para quem fica! Apartamento de 2 Dorms, com opção de terraço e itens compartilhados. Lazer completo e torre única!
- 550M da estação Barra Funda;
- 5Min do Allianz Parque;
- 7M do Bourbon Shopping;
- 8M da Uninove Memorial.
**Garanta Já! Fale agora mesmo com um consultor online e faça uma simulação.**
#### Imagens
  * Decorado
  * Foto Ilustrativa
  * Plantas
  * Vídeo tour 


  * 

  * 

  *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   * 

  *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   * 

  *   *   *   *   * 

  *   *   *   *   * 

Áreas comuns
#### Diferenciais
  * Piscina Adulto
  * Piscina infantil
  * Easy Market
  * Salão de festas
  * Churrasqueira
  * Lavanderia
  * Food Square
  * Fitness
  * Espaço Fitness ao Ar Livre
  * Espaço Pet
  * Praça de Convivência
  * Playground
  * Sala de descanso com sauna
  * Office space
  * Bar
  * Oficina
  * Salão de jogos
  * Brinquedoteca
  * Piso Laminado nos Dorms
  * Duplo acionamento no vaso sanitário

Ver todos
Em Obras
Piscina Adulto
Piscina infantil
Easy Market
Fale com um corretor
×
#### Acompanhamento de obras
Mobiliz. Canteiro
100%
Fundação
100%
Estrutura
2%
Alvenaria
0%
Acabamento interno
0%
Acabamento externo
0%
Inst. Elétricas
1%
Inst. Hidráulicas
3%
Pintura
0%
Serv. Complementares
11%
  *   * 

#### Localização
Empreendimento
#### Avenida Antártica, 1, Barra Funda. São Paulo - SP
Veja como chegar
Waze Google Maps
Clique para exibir o mapa
Avenida Antártica , 1 - Barra Funda 
#### Sobre a região
A **Zona Oeste de São Paulo** tem facilidade de locomoção, diversidade de comércios, instituições de ensino, e infinitas opções de lazer e cultura. Tudo isso em excelentes bairros, como: Barra Funda, Vila Madalena, Pinheiros, Sumaré, entre outros. 
O estilo de vida com facilidades, qualidade e mobilidade urbana atraem pessoas de todas as idades para morar na Zona Oeste.  

####  Imóveis relacionados 
Breve Lançamento
#### Cury Máximo Butantã
Butantã
2 Dorms, opção de terraço, suíte e lazer
Salão de Festas
Churrasqueira
Sport Bar
Quadra Gramada
Lançamento
#### Cury Cidade Jaguaré - Vila Pinheiros
Jaguaré
2 Dorms, lazer completo, com opção de varanda
Piscina Adulto
Piscina infantil
Cine open air
Mini quadra
Em Obras
#### Cury Flow Barra Funda
Barra Funda
2 Dorms, lazer completo e opção de terraço
Piscina Adulto
Piscina infantil
Churrasqueira
Salão de festas
CISA62 Incorporadora LTDA. Condomínio residencial Flow Barra Funda II. Incorporação registrada em 22/04/2021, Sob R. 3 da matricula 273.784, do 15º Oficial de registro de imóveis de São Paulo. Creci SP 23670-J - Responsável Técnico Ronaldo Cury de Capua 
* * *
Utilizamos cookies essenciais e tecnologias semelhantes e, ao continuar navegando, você concorda com estas condições.
Para mais informações, confira nossa Política de Privacidade e Política de cookies
OK
##### Sobre
  * Conheça a Cury
  * Regiões
  * Área do Cliente


##### Vendas
  * Imóveis
  * Simular Financiamento
  * Fale com um Corretor


##### Comunicação
  * Contato
  * Assessoria de Imprensa
  * Relações com Investidores


##### Cury nas redes
* * *
* * *
Cury Construtora e Incorporadora S/A 2025 - CRECI 24719-J. Todos os direitos reservados. 
Confira a nossa Política de Privacidade e Política de cookies
Ok
Ofereça seu terreno 
Quero vender meu terreno em: 
São Paulo Rio de Janeiro
Envie um e-mail para adefinir@cury.net com seu **nome** , **telefone** , **área do terreno** e **localização**. 
Ou se preferir, clique aqui   
para cadastrar o seu terreno 
Assessoria de Imprensa 
E-mail: cury@maquinacohnwolfe.com 
; 
Ok
### Control your privacy
AdOpt
Our website uses cookies to improve navigation. Privacy Policy - Terms of use Developed by AdOpt
Customize Reject Accept


# Liens externes trouvés
- https://cury.gupy.io/
- http://www.relacionamentocury.com.br/
- https://api.whatsapp.com/send?phone=5521999923476&text=Olá! Tenho interesse em saber mais sobre o imóvel Cury Flow Barra Funda 2.
- https://waze.com/ul?ll=-23.521542,-46.667842&navigate=yes
- https://maps.google.com/maps?daddr=-23.521542,-46.667842
- https://www.facebook.com/CuryConstrutora?fref=ts
- https://www.instagram.com/curyconstrutora/
- https://twitter.com/curyconstrutora
- https://www.youtube.com/user/curyconstrutora
- https://www.linkedin.com/company/cury-construtora/
- https://br.pinterest.com/curyconstrutoranet/
- https://www.tiktok.com/@curyconstrutora
- https://open.spotify.com/user/7ibqq6hybxooqerqc8ywnhqe9?si=5WTqJRxfRo6-3RoYe20vYA&nd=1
- adefinir@cury.net
- https://goadopt.io/en/porque-aviso/?utm_content=main&utm_medium=cookie_banner_web&utm_source=cookie_banner_d44972e9-1283-4d1b-b2de-6c0653a2c941
- https://hub.goadopt.io/document/2d556213-4359-44cf-a319-278f1de4e405
- https://hub.goadopt.io/document/b059c8cf-5787-49fc-9c2a-d24fd98d1b2f
  * Imóveis 
  * Cury 
  * Serviços 
  * Área do Cliente
  * São Paulo


  * São Paulo  Rio de Janeiro 


  * Imóveis 
Cury
  * Serviços
  *   * Área do Cliente 


Em Obras
Barra Funda
### Cury Flow Barra Funda
2 dorms. 
Fale com um corretor
Fale com um corretor 
  * Sobre o imóvel
* * *
{ 
  * Imagens
* * *
  * Diferenciais
* * *
  * Mapa
* * *
  * Obras
* * *


Fale com um corretor 
  * Sobre o imóvel
* * *
  * Imagens
* * *
  * Diferenciais
* * *
  * Mapa
* * *
  * Obras
* * *


Viva a cada momento dentro do Flow Barra Funda! Aproveite o que ele tem de melhor: Tranquilidade, Conforto e Lazer Completo. 
Apartamento de 2 Dorms, opção de terraço pertinho da estação Barra Funda e Shopping Bourbon. 
  

#### Imagens
  * Decorado
  * Foto Ilustrativa
  * Vídeo tour 


  *   *   *   *   *   *   *   *   * 

  *   *   *   *   *   *   *   *   * 

  *   *   *   *   *   *   *   *   *   *   * 

  *   *   *   *   *   *   *   *   *   *   * 

Áreas comuns
#### Diferenciais
  * Piscina Adulto
  * Piscina infantil
  * Churrasqueira
  * Salão de festas
  * Espaço Pet
  * Fitness
  * Lavanderia
  * Food Square
  * Espaço Fitness ao Ar Livre
  * Playground
  * Office space
  * Oficina
  * Brinquedoteca
  * sala de games
  * Piso Laminado nos dorms
  * Duplo acionamento no vaso sanitário

Ver todos
Em Obras
Piscina Adulto
Piscina infantil
Churrasqueira
Fale com um corretor
×
#### Acompanhamento de obras
Mobiliz. Canteiro
100%
Fundação
100%
Estrutura
8%
Alvenaria
5%
Acabamento interno
0%
Acabamento externo
0%
Inst. Elétricas
3%
Inst. Hidráulicas
6%
Pintura
0%
Serv. Complementares
13%
  *   *   * 

#### Localização
Empreendimento
#### Avenida Antártica, 1, Barra Funda. São Paulo - SP
Veja como chegar
Waze Google Maps
Clique para exibir o mapa
Avenida Antártica , 1 - Barra Funda 
#### Sobre a região
A **Zona Oeste de São Paulo** tem facilidade de locomoção, diversidade de comércios, instituições de ensino, e infinitas opções de lazer e cultura. Tudo isso em excelentes bairros, como: Barra Funda, Vila Madalena, Pinheiros, Sumaré, entre outros. 
O estilo de vida com facilidades, qualidade e mobilidade urbana atraem pessoas de todas as idades para morar na Zona Oeste.  

####  Imóveis relacionados 
Breve Lançamento
#### Cury Máximo Butantã
Butantã
2 Dorms, opção de terraço, suíte e lazer
Salão de Festas
Churrasqueira
Sport Bar
Quadra Gramada
Lançamento
#### Cury Cidade Jaguaré - Vila Pinheiros
Jaguaré
2 Dorms, lazer completo, com opção de varanda
Piscina Adulto
Piscina infantil
Cine open air
Mini quadra
Em Obras
#### Cury Flow Barra Funda 2
Barra Funda
2 Dorms, com terraço e itens compartilhados
Piscina Adulto
Piscina infantil
Easy Market
Salão de festas
CCISA62 INCORPORADORA LTDA (CONDOMÍNIO RESIDENCIAL FLOW BARRA FUNDA). INCORPORAÇÃO REGISTRADA EM 23/02/2021, SOB R. 3 DA MATRÍCULA 273.780, DO 15º OFICIAL DE REGISTRO DE IMÓVEIS DE SÃO PAULO. Creci SP 23670-J - Responsável Técnico Ronaldo Cury de Capua   

* * *
Utilizamos cookies essenciais e tecnologias semelhantes e, ao continuar navegando, você concorda com estas condições.
Para mais informações, confira nossa Política de Privacidade e Política de cookies
OK
##### Sobre
  * Conheça a Cury
  * Regiões
  * Área do Cliente


##### Vendas
  * Imóveis
  * Simular Financiamento
  * Fale com um Corretor


##### Comunicação
  * Contato
  * Assessoria de Imprensa
  * Relações com Investidores


##### Cury nas redes
* * *
* * *
Cury Construtora e Incorporadora S/A 2025 - CRECI 24719-J. Todos os direitos reservados. 
Confira a nossa Política de Privacidade e Política de cookies
Ok
Ofereça seu terreno 
Quero vender meu terreno em: 
São Paulo Rio de Janeiro
Envie um e-mail para adefinir@cury.net com seu **nome** , **telefone** , **área do terreno** e **localização**. 
Ou se preferir, clique aqui   
para cadastrar o seu terreno 
Assessoria de Imprensa 
E-mail: cury@maquinacohnwolfe.com 
; 
Ok
### Control your privacy
AdOpt
Our website uses cookies to improve navigation. Privacy Policy - Terms of use Developed by AdOpt
Customize Reject Accept


# Liens externes trouvés
- https://cury.gupy.io/
- http://www.relacionamentocury.com.br/
- https://api.whatsapp.com/send?phone=5521999923476&text=Olá! Tenho interesse em saber mais sobre o imóvel Cury Flow Barra Funda.
- https://waze.com/ul?ll=-23.521542,-46.667842&navigate=yes
- https://maps.google.com/maps?daddr=-23.521542,-46.667842
- https://www.facebook.com/CuryConstrutora?fref=ts
- https://www.instagram.com/curyconstrutora/
- https://twitter.com/curyconstrutora
- https://www.youtube.com/user/curyconstrutora
- https://www.linkedin.com/company/cury-construtora/
- https://br.pinterest.com/curyconstrutoranet/
- https://www.tiktok.com/@curyconstrutora
- https://open.spotify.com/user/7ibqq6hybxooqerqc8ywnhqe9?si=5WTqJRxfRo6-3RoYe20vYA&nd=1
- adefinir@cury.net
- https://goadopt.io/en/porque-aviso/?utm_content=main&utm_medium=cookie_banner_web&utm_source=cookie_banner_d44972e9-1283-4d1b-b2de-6c0653a2c941
- https://hub.goadopt.io/document/2d556213-4359-44cf-a319-278f1de4e405
- https://hub.goadopt.io/document/b059c8cf-5787-49fc-9c2a-d24fd98d1b2f
  * Imóveis 
  * Cury 
  * Serviços 
  * Área do Cliente
  * São Paulo


  * São Paulo  Rio de Janeiro 


  * Imóveis 
Cury
  * Serviços
  *   * Área do Cliente 


Voltar
## Corretor
Coloque suas informações nos campos a seguir e será gerado um link que irá diretamente para seu e-mail para você poder enviar para o seu cliente. Fique tranquilo! Pois a documentação que o cliente anexar aqui você terá total acesso e não irá para nenhum banco de dados. Com a documentação do seu cliente em mãos, poderá cadastrar a pasta e prosseguir com o atendimento. 
Nome: E-mail Empreedimento Ar.que Blue Lyne Pirituba NOVO Cury Dez João Dias Cury Casabella Cury Cenário Taboão Cury Cidade Jaguaré - Vila Pinheiros Cury Cidade Mooca Cury Cidade Mooca Vila Palermo Cury Dez Anhaia Mello Cury Dez Aricanduva Cury Dez Bom Retiro Cury Dez Bom Retiro 2 Cury Dez Cantareira Cury Dez Celeste Cury Dez Cerejeira Cury Dez Cursino Cury Dez Eucalipto Cury Dez Gamelinha Cury Dez Gamelinha 2 Cury Dez Guarapiranga Cury Dez Ipiranga Cury Dez Ipiranga 2 Cury Dez Jardim Botânico Cury Dez Miguel Yunes Cury Dez Ourives Cury Dez Parque das Bandeiras Cury Dez Parque do Carmo Cury Dez Penha Cury Dez Praia Grande Cury Dez Sacomã Cury Dez São Miguel Cury Dez São Miguel 2 Cury Dez Tatuapé Cury Dez Tiquatira Cury Dez Vila Curuçá Cury Dez Vila das Belezas Cury Dez Vila das Belezas 2 Cury Dez Vila Ema Cury Dez Vila Guilherme Cury Flex Mogi Cury Flow Barra Funda Cury Flow Barra Funda 2 Cury Jardim Cury Máximo Butantã Cury Máximo Mogi Cury Máximo Zona Sul Cury Mérito Aricanduva Cury Mérito Guarapiranga Cury Mérito Penha Cury Mérito Sabará Cury Mérito Tiquatira Cury Mérito Vila Curuçá Cury Mérito Vila Maria Cury Meu Lar Cantareira Cury Meu Lar Jaraguá Cury Meu Lar Mogi Cury Meu Lar Mogi 2 Cury Meu Lar Monte Mor Cury Meu Lar Pirituba Cury Parque dos Sonhos Buriti Cury Parque dos Sonhos Figueiras Cury Parque dos Sonhos Ipês Cury Parque dos Sonhos Jacarandá Cury Parque dos Sonhos Manacá Cury Parque dos Sonhos Sapucaia Cury Ritmo Condomínio Clube Cury Square Panamby Cury SuperCittà Alegria Cury SuperCittà Horizonte Cury SuperCittà Jardins Cury Supercittà Magia Cury Supercittá Paraiso Cury Único Jacu Pêssego Cury Único Mogi Cury Único Penha Cury Único Sacomã Cury Único Suzano Cury Único Zona Sul Cury Urban Barra Funda Cury Urban Barra Funda 2 Cury Urban Mooca Cury Urban Mooca 2 Cury Urban Parque das Bandeiras Cury Verano Praia & Clube Cury Vila Nova Urupês Cury Viva Mais Itaquá Dez Cury Canindé Green Lyne Pirituba Guedala Park Premium Lyne Pirituba My Miguel Yunes Plantão para testes 2 Square Panamby Itapaiuna   
Enviar
Utilizamos cookies essenciais e tecnologias semelhantes e, ao continuar navegando, você concorda com estas condições.
Para mais informações, confira nossa Política de Privacidade e Política de cookies
OK
##### Sobre
  * Conheça a Cury
  * Regiões
  * Área do Cliente


##### Vendas
  * Imóveis
  * Simular Financiamento
  * Fale com um Corretor


##### Comunicação
  * Contato
  * Assessoria de Imprensa
  * Relações com Investidores


##### Cury nas redes
* * *
* * *
Cury Construtora e Incorporadora S/A 2025 - CRECI 24719-J. Todos os direitos reservados. 
Confira a nossa Política de Privacidade e Política de cookies
Ok
Ofereça seu terreno 
Quero vender meu terreno em: 
São Paulo Rio de Janeiro
Envie um e-mail para adefinir@cury.net com seu **nome** , **telefone** , **área do terreno** e **localização**. 
Ou se preferir, clique aqui   
para cadastrar o seu terreno 
Assessoria de Imprensa 
E-mail: cury@maquinacohnwolfe.com 
; 
Ok
### Control your privacy
AdOpt
Our website uses cookies to improve navigation. Privacy Policy - Terms of use Developed by AdOpt
Customize Reject Accept


# Liens externes trouvés
- https://cury.gupy.io/
- http://www.relacionamentocury.com.br/
- https://api.whatsapp.com/send?phone=5521999923476&text=Olá! Tenho interesse em saber mais sobre a Cury Construtora SP
- javascript:history.back();
- https://www.facebook.com/CuryConstrutora?fref=ts
- https://www.instagram.com/curyconstrutora/
- https://twitter.com/curyconstrutora
- https://www.youtube.com/user/curyconstrutora
- https://www.linkedin.com/company/cury-construtora/
- https://br.pinterest.com/curyconstrutoranet/
- https://www.tiktok.com/@curyconstrutora
- https://open.spotify.com/user/7ibqq6hybxooqerqc8ywnhqe9?si=5WTqJRxfRo6-3RoYe20vYA&nd=1
- adefinir@cury.net
- https://goadopt.io/en/porque-aviso/?utm_content=main&utm_medium=cookie_banner_web&utm_source=cookie_banner_d44972e9-1283-4d1b-b2de-6c0653a2c941
- https://hub.goadopt.io/document/2d556213-4359-44cf-a319-278f1de4e405
- https://hub.goadopt.io/document/b059c8cf-5787-49fc-9c2a-d24fd98d1b2f
Relações com Investidores
Institucional
PTEN
  * SOBRE A CURY
    * Histórico
    * Perfil Corporativo
    * Conheça a Cury
  * GOVERNANÇA CORPORATIVA
    * Diretoria, Conselhos, Comitê e Comissões
    * Composição Acionária
    * Estatuto Social, Regimentos e Políticas
    * Assembleias e RCA
    * Código de Conduta
  * INFORMAÇÕES AOS INVESTIDORES
    * Central de Resultados
    * Classificação de Risco
    * Documentos CVM
    * Apresentação Institucional
    * Planilha Interativa
    * Histórico de Proventos
    * Relatório de Sustentabilidade – ESG
  * SERVIÇOS AOS INVESTIDORES
    * Fale com RI
    * Calendário de Eventos
    * Cobertura de Analistas
    * Cadastre-se no Mailing
    * Cotações e Gráficos
    * Perguntas Frequentes – Novo


  *   *   * 

  * CURY3
  * R$ 29,52
  * 1,10%
  * IBOV
  * 138.855
  * 1,45%
  * IMOB
  * 1.110,44
  * 1,65%


Powered by MZ


# Liens externes trouvés
- javascript:void(0)
- https://www.facebook.com/CuryConstrutora?fref=ts
- https://www.linkedin.com/company/cury-construtora/
- https://www.instagram.com/curyconstrutora/
- https://www.mzgroup.com/
Relações com Investidores
Institucional
PTEN
  * SOBRE A CURY
    * Histórico
    * Perfil Corporativo
    * Conheça a Cury
  * GOVERNANÇA CORPORATIVA
    * Diretoria, Conselhos, Comitê e Comissões
    * Composição Acionária
    * Estatuto Social, Regimentos e Políticas
    * Assembleias e RCA
    * Código de Conduta
  * INFORMAÇÕES AOS INVESTIDORES
    * Central de Resultados
    * Classificação de Risco
    * Documentos CVM
    * Apresentação Institucional
    * Planilha Interativa
    * Histórico de Proventos
    * Relatório de Sustentabilidade – ESG
  * SERVIÇOS AOS INVESTIDORES
    * Fale com RI
    * Calendário de Eventos
    * Cobertura de Analistas
    * Cadastre-se no Mailing
    * Cotações e Gráficos
    * Perguntas Frequentes – Novo


  *   *   * 

  * CURY3
  * R$ 29,52
  * 1,10%
  * IBOV
  * 138.855
  * 1,45%
  * IMOB
  * 1.110,44
  * 1,65%


Powered by MZ
Portuguese
English
×
Este website usa cookies
Nós utilizamos cookies para otimizar e aprimorar sua navegação do site, manter uma melhoria contínua no conteúdo oferecido e aperfeiçoar a experiência de nossos usuários. Todos os cookies, exceto os essenciais, necessitam de seu consentimento para serem executados. Para saber mais acesse nosso Aviso de Privacidade e o nosso Aviso de Cookies.
Estritamente necessários
Direcionamento
Funcionalidade
Mostrar detalhes Esconder detalhes
Salvar e Fechar
Aceitar todos
Recusar todos


# Liens externes trouvés
- javascript:void(0)
- https://www.facebook.com/CuryConstrutora?fref=ts
- https://www.linkedin.com/company/cury-construtora/
- https://www.instagram.com/curyconstrutora/
- https://www.mzgroup.com/
  * Imóveis 
  * Cury 
  * Serviços 
  * Área do Cliente
  * São Paulo


  * São Paulo  Rio de Janeiro 


  * Imóveis 
Cury
  * Serviços
  *   * Área do Cliente 


## Simulador de Financiamento
1
2
3
4
## Simulador de Financiamento
#### Quer uma rápida previsão de como pagar seu imóvel? **Faça uma simulação**
Para começar, selecione a região: Região Campinas  Centro  Interior  Litoral  Santo André  Zona Leste  Zona lost  Zona Norte  Zona Oeste  Zona Sul 
Avançar 
Qual o seu nome?
Anterior Próximo
Qual o seu melhor email?
Aceito receber contato por e-mail
Anterior Próximo
Qual o seu telefone (com DDD)?
Aceito receber contato por telefone
Aceito receber contato por SMS
Aceito receber contato por WhatsApp
Anterior Próximo
Agradecemos pelas informações   
  
Um de nossos consultores irá entrar em contato com você informando o código 
Utilizamos cookies essenciais e tecnologias semelhantes e, ao continuar navegando, você concorda com estas condições.
Para mais informações, confira nossa Política de Privacidade e Política de cookies
OK
##### Sobre
  * Conheça a Cury
  * Regiões
  * Área do Cliente


##### Vendas
  * Imóveis
  * Simular Financiamento
  * Fale com um Corretor


##### Comunicação
  * Contato
  * Assessoria de Imprensa
  * Relações com Investidores


##### Cury nas redes
* * *
* * *
Cury Construtora e Incorporadora S/A 2025 - CRECI 24719-J. Todos os direitos reservados. 
Confira a nossa Política de Privacidade e Política de cookies
Ok
Ofereça seu terreno 
Quero vender meu terreno em: 
São Paulo Rio de Janeiro
Envie um e-mail para adefinir@cury.net com seu **nome** , **telefone** , **área do terreno** e **localização**. 
Ou se preferir, clique aqui   
para cadastrar o seu terreno 
Assessoria de Imprensa 
E-mail: cury@maquinacohnwolfe.com 
; 
Ok
### Control your privacy
AdOpt
Our website uses cookies to improve navigation. Privacy Policy - Terms of use Developed by AdOpt
Customize Reject Accept


# Liens externes trouvés
- https://cury.gupy.io/
- http://www.relacionamentocury.com.br/
- https://api.whatsapp.com/send?phone=5521999923476&text=Olá! Tenho interesse em saber mais sobre a Cury Construtora SP
- https://www.facebook.com/CuryConstrutora?fref=ts
- https://www.instagram.com/curyconstrutora/
- https://twitter.com/curyconstrutora
- https://www.youtube.com/user/curyconstrutora
- https://www.linkedin.com/company/cury-construtora/
- https://br.pinterest.com/curyconstrutoranet/
- https://www.tiktok.com/@curyconstrutora
- https://open.spotify.com/user/7ibqq6hybxooqerqc8ywnhqe9?si=5WTqJRxfRo6-3RoYe20vYA&nd=1
- adefinir@cury.net
- https://goadopt.io/en/porque-aviso/?utm_content=main&utm_medium=cookie_banner_web&utm_source=cookie_banner_d44972e9-1283-4d1b-b2de-6c0653a2c941
- https://hub.goadopt.io/document/2d556213-4359-44cf-a319-278f1de4e405
- https://hub.goadopt.io/document/b059c8cf-5787-49fc-9c2a-d24fd98d1b2f
  * Imóveis 
  * Cury 
  * Serviços 
  * Área do Cliente
  * São Paulo


  * São Paulo  Rio de Janeiro 


  * Imóveis 
Cury
  * Serviços
  *   * Área do Cliente 


## TV Cury
Encontre seu vídeo
Todas as categorias Empreendimento Régua de Negócios Campanha Acompanhamento de Obras Rio Entrega de Chaves É tudo nosso
#### Últimos vídeos
  * ENTREGA DE CHAVES
  * Virada Cury 18 SP
  * Compra Definitiva - Cury
  * É Tudo Nosso – Episódio 2 | O chuveiro
  * É Tudo Nosso - Episódio 3 | Lacre de segurança
  * É Tudo Nosso - Episódio 4 | Infiltrações
  * É Tudo Nosso - Episódio 5 | Reformas
  * É Tudo Nosso - Episódio 6 | Tomadas e benjamins
  * É Tudo Nosso - Episódio 7 | Cuidados com a limpeza do imóvel
  * É Tudo Nosso - Episódio 8 | Tubulações, pias e ralos


Mais vídeos
Utilizamos cookies essenciais e tecnologias semelhantes e, ao continuar navegando, você concorda com estas condições.
Para mais informações, confira nossa Política de Privacidade e Política de cookies
OK
##### Sobre
  * Conheça a Cury
  * Regiões
  * Área do Cliente


##### Vendas
  * Imóveis
  * Simular Financiamento
  * Fale com um Corretor


##### Comunicação
  * Contato
  * Assessoria de Imprensa
  * Relações com Investidores


##### Cury nas redes
* * *
* * *
Cury Construtora e Incorporadora S/A 2025 - CRECI 24719-J. Todos os direitos reservados. 
Confira a nossa Política de Privacidade e Política de cookies
Ok
Ofereça seu terreno 
Quero vender meu terreno em: 
São Paulo Rio de Janeiro
Envie um e-mail para adefinir@cury.net com seu **nome** , **telefone** , **área do terreno** e **localização**. 
Ou se preferir, clique aqui   
para cadastrar o seu terreno 
Assessoria de Imprensa 
E-mail: cury@maquinacohnwolfe.com 
; 
Ok
### Control your privacy
AdOpt
Our website uses cookies to improve navigation. Privacy Policy - Terms of use Developed by AdOpt
Customize Reject Accept


# Liens externes trouvés
- https://cury.gupy.io/
- http://www.relacionamentocury.com.br/
- https://api.whatsapp.com/send?phone=5521999923476&text=Olá! Tenho interesse em saber mais sobre a Cury Construtora SP
- https://www.facebook.com/CuryConstrutora?fref=ts
- https://www.instagram.com/curyconstrutora/
- https://twitter.com/curyconstrutora
- https://www.youtube.com/user/curyconstrutora
- https://www.linkedin.com/company/cury-construtora/
- https://br.pinterest.com/curyconstrutoranet/
- https://www.tiktok.com/@curyconstrutora
- https://open.spotify.com/user/7ibqq6hybxooqerqc8ywnhqe9?si=5WTqJRxfRo6-3RoYe20vYA&nd=1
- adefinir@cury.net
- https://goadopt.io/en/porque-aviso/?utm_content=main&utm_medium=cookie_banner_web&utm_source=cookie_banner_d44972e9-1283-4d1b-b2de-6c0653a2c941
- https://hub.goadopt.io/document/2d556213-4359-44cf-a319-278f1de4e405
- https://hub.goadopt.io/document/b059c8cf-5787-49fc-9c2a-d24fd98d1b2f
  * Imóveis 
  * Cury 
  * Serviços 
  * Área do Cliente
  * São Paulo


  * São Paulo  Rio de Janeiro 


  * Imóveis 
Cury
  * Serviços
  *   * Área do Cliente 


## Regiões
Selecione o estado para mais detalhes
São Paulo Rio de Janeiro
####  Regiões em São Paulo
  * Zona lost
  * Santo André
  * Campinas
  * Zona Norte
  * Zona Sul
  * Zona Leste
  * Zona Oeste
  * Centro
  * Litoral
  * Interior


Veja mais regiões
Utilizamos cookies essenciais e tecnologias semelhantes e, ao continuar navegando, você concorda com estas condições.
Para mais informações, confira nossa Política de Privacidade e Política de cookies
OK
##### Sobre
  * Conheça a Cury
  * Regiões
  * Área do Cliente


##### Vendas
  * Imóveis
  * Simular Financiamento
  * Fale com um Corretor


##### Comunicação
  * Contato
  * Assessoria de Imprensa
  * Relações com Investidores


##### Cury nas redes
* * *
* * *
Cury Construtora e Incorporadora S/A 2025 - CRECI 24719-J. Todos os direitos reservados. 
Confira a nossa Política de Privacidade e Política de cookies
Ok
Ofereça seu terreno 
Quero vender meu terreno em: 
São Paulo Rio de Janeiro
Envie um e-mail para adefinir@cury.net com seu **nome** , **telefone** , **área do terreno** e **localização**. 
Ou se preferir, clique aqui   
para cadastrar o seu terreno 
Assessoria de Imprensa 
E-mail: cury@maquinacohnwolfe.com 
; 
Ok
### Control your privacy
AdOpt
Our website uses cookies to improve navigation. Privacy Policy - Terms of use Developed by AdOpt
Customize Reject Accept


# Liens externes trouvés
- https://cury.gupy.io/
- http://www.relacionamentocury.com.br/
- https://api.whatsapp.com/send?phone=5521999923476&text=Olá! Tenho interesse em saber mais sobre a Cury Construtora SP
- https://www.facebook.com/CuryConstrutora?fref=ts
- https://www.instagram.com/curyconstrutora/
- https://twitter.com/curyconstrutora
- https://www.youtube.com/user/curyconstrutora
- https://www.linkedin.com/company/cury-construtora/
- https://br.pinterest.com/curyconstrutoranet/
- https://www.tiktok.com/@curyconstrutora
- https://open.spotify.com/user/7ibqq6hybxooqerqc8ywnhqe9?si=5WTqJRxfRo6-3RoYe20vYA&nd=1
- adefinir@cury.net
- https://goadopt.io/en/porque-aviso/?utm_content=main&utm_medium=cookie_banner_web&utm_source=cookie_banner_d44972e9-1283-4d1b-b2de-6c0653a2c941
- https://hub.goadopt.io/document/2d556213-4359-44cf-a319-278f1de4e405
- https://hub.goadopt.io/document/b059c8cf-5787-49fc-9c2a-d24fd98d1b2f
  * Imóveis 
  * Cury 
  * Serviços 
  * Área do Cliente
  * São Paulo


  * São Paulo  Rio de Janeiro 


  * Imóveis 
Cury
  * Serviços
  *   * Área do Cliente 


## Conheça a Cury
Institucional  Governança  Certificados  Prêmios  Ações Sociais  Programas Internos  Sustentabilidade  Programas para clientes  Ações - Porto Maravilha  Relatório de igualdade salarial  Teste Sustentabilidade  Instituto Cury 
  * Institucional 
  * Governança 
  * Certificados 
  * Prêmios 
  * Ações Sociais 
  * Programas Internos 
  * Sustentabilidade 
  * Programas para clientes 
  * Ações - Porto Maravilha 
  * Relatório de igualdade salarial 
  * Teste Sustentabilidade 
  * Instituto Cury 


#### Institucional
A Cury Construtora iniciou sua história em 7 de maio de 1963 e desde o início tem o objetivo de buscar sempre melhorias e inovações constantes.  
Em 4 de julho de 2007 a Cury passou a ser Cury Construtora e Incorporadora S.A., fruto de uma joint-venture entre Cyrela Brazil Realty e Cury Empreendimentos. Já nascemos com mais de 40 anos de experiência e seguimos possuindo qualidade em nossas obras aliadas ao valor acessível para o nosso público-alvo que se encaixa no programa Casa Verde e Amarela.  
Além de certificados reconhecidos no mercado, também possuímos diversos prêmios imobiliários no decorrer dos anos.  
Mas o maior reconhecimento está na satisfação de nossos clientes e na realização do sonho de milhares de pessoas que valorizam e usufruem do rigor na escolha dos endereços, do alto padrão de construção, da perfeição do acabamento e do restrito cumprimento dos prazos, princípios que fazem da Cury, cada vez mais, a construtora da sua casa.  
Em 2020 realizamos nosso IPO e entramos na B3, a Bolsa de Valores Brasileira. Com mais esse marco histórico, estamos ainda mais focados na nossa missão de reduzir o déficit habitacional e ser a construtora número 1 dos brasileiros.  
  
Confira mais sobre a Cury.
#### Princípios Essenciais
### Missão
Trabalhar ativamente para o desenvolvimento socioeconômico do País, oferecendo qualidade de alto padrão na construção, tempo hábil na entrega e bom atendimento aos seus clientes, contribuindo, desse modo, para a diminuição do déficit habitacional do Brasil.
### Visão
Investir em inovação e aprimoramento contínuo para ser referência em seu ramo de atuação, atendendo às expectativas, às necessidades e aos interesses de seus clientes, funcionários e acionistas.
### Valores
Ética Responsabilidade Transparência Competência Solidez
#### Endereços e contatos
**São Paulo**
Rua Funchal, 411 - 1º andar Vila Olímpia - São Paulo - SP Telefone: (11) 3117-1300
**Rio de Janeiro**
Rua Buenos Aires, 48, 5º andar Centro - Rio de Janeiro/RJ Telefone: (21) 3543-6888
**Vendas SP**
Rua Roberto Bosch, 544 Barra Funda - São Paulo/SP Telefone: (11) 3117-1313
**Comercial e Vendas RJ**
Avenida Rio Branco, 131, 21º andar Centro - Rio de Janeiro/RJ Telefone: (21) 3554-3350
**Relacionamento**
Central de Relacionamento: SP (11) 3117-1300, RJ (21) 3543- 6887 e 0800 314 9696 - somente fixo interior e litoral de SP, de segunda-feira a sexta-feira das 09h às 16h.
Utilizamos cookies essenciais e tecnologias semelhantes e, ao continuar navegando, você concorda com estas condições.
Para mais informações, confira nossa Política de Privacidade e Política de cookies
OK
##### Sobre
  * Conheça a Cury
  * Regiões
  * Área do Cliente


##### Vendas
  * Imóveis
  * Simular Financiamento
  * Fale com um Corretor


##### Comunicação
  * Contato
  * Assessoria de Imprensa
  * Relações com Investidores


##### Cury nas redes
* * *
* * *
Cury Construtora e Incorporadora S/A 2025 - CRECI 24719-J. Todos os direitos reservados. 
Confira a nossa Política de Privacidade e Política de cookies
Ok
Ofereça seu terreno 
Quero vender meu terreno em: 
São Paulo Rio de Janeiro
Envie um e-mail para adefinir@cury.net com seu **nome** , **telefone** , **área do terreno** e **localização**. 
Ou se preferir, clique aqui   
para cadastrar o seu terreno 
Assessoria de Imprensa 
E-mail: cury@maquinacohnwolfe.com 
; 
Ok
### Control your privacy
AdOpt
Our website uses cookies to improve navigation. Privacy Policy - Terms of use Developed by AdOpt
Customize Reject Accept


# Liens externes trouvés
- https://cury.gupy.io/
- http://www.relacionamentocury.com.br/
- https://api.whatsapp.com/send?phone=5521999923476&text=Olá! Tenho interesse em saber mais sobre a Cury Construtora SP
- https://www.facebook.com/CuryConstrutora?fref=ts
- https://www.instagram.com/curyconstrutora/
- https://twitter.com/curyconstrutora
- https://www.youtube.com/user/curyconstrutora
- https://www.linkedin.com/company/cury-construtora/
- https://br.pinterest.com/curyconstrutoranet/
- https://www.tiktok.com/@curyconstrutora
- https://open.spotify.com/user/7ibqq6hybxooqerqc8ywnhqe9?si=5WTqJRxfRo6-3RoYe20vYA&nd=1
- adefinir@cury.net
- https://goadopt.io/en/porque-aviso/?utm_content=main&utm_medium=cookie_banner_web&utm_source=cookie_banner_d44972e9-1283-4d1b-b2de-6c0653a2c941
- https://hub.goadopt.io/document/2d556213-4359-44cf-a319-278f1de4e405
- https://hub.goadopt.io/document/b059c8cf-5787-49fc-9c2a-d24fd98d1b2f
  * Imóveis 
  * Cury 
  * Serviços 
  * Área do Cliente
  * São Paulo


  * São Paulo  Rio de Janeiro 


  * Imóveis 
Cury
  * Serviços
  *   * Área do Cliente 


## Política de Privacidade
## 
A sua privacidade e o sigilo de suas informações são prioridade para a Cury. Sempre que você nos procura, utiliza nossos serviços ou adquire nossos produtos, adotamos as medidas necessárias para proteger seus dados pessoais, garantir sua confidencialidade e assegurar o uso adequado das informações, em conformidade com a legislação aplicável.
  

## Quem Somos
## 
A Cury S/A, cadastrada sob o CNPJ 08.797.760/0001-83 e suas Sociedades de Propósito Específico (SPEs) são responsáveis pela incorporação e construção de empreendimentos residenciais nos estados de São Paulo e Rio de Janeiro, especialmente no âmbito dos programas Minha Casa Minha Vida e Casa Verde e Amarela. Nossas empresas utilizam uma estrutura compartilhada de recursos, incluindo tecnologia e sistemas, o que permite maior eficiência em nossas operações. 
Por essa razão, para os fins desta Política de Privacidade, você deve considerar não apenas a Cury S/A como a controladora dos seus dados pessoais, mas também as demais empresas que integram nosso grupo empresarial, conforme o empreendimento que você tenha interesse ou tenha adquirido. 
Comprometemo-nos a proteger seus dados pessoais e respeitar a sua privacidade. Para que você compreenda como coletamos, armazenamos e tratamos seus dados, apresentamos esta Política de Privacidade (doravante referida como "Política"). 
  

## Para quem se aplica
## 
Esta Política de Privacidade aplica-se aos titulares de dados pessoais, isto é, a todas as pessoas que tenham seus dados pessoais tratados pela Cury. 
Isso inclui clientes, colaboradores, usuários, fornecedores, acionistas e quaisquer outros indivíduos que mantenham algum tipo de relação com a empresa. Mesmo que você esteja apenas visitando nosso site para conhecer nossa empresa e nossos empreendimentos, esta Política foi desenvolvida para proteger os seus direitos e regular o tratamento de seus dados pessoais.
  

## Deseja informações sobre seus dados pessoais armazenados pela Cury?
## 
Consulte aqui e daremos todas as informações necessárias.
  

##  Fique Atento 
## 
Para que possamos garantir o sigilo e proteção dos seus dados pessoais, é importante que você também tome os seguintes cuidados: 
• utilize apenas os canais oficiais disponibilizados pela Cury; 
• atente-se para a origem das mensagens, não acessando o nosso site por meio de links recebidos por e-mail, SMS, WhatsApp, Telegram e outros de fontes que não seja da própria Cury e suas empresas coligadas, sendo que em caso de dúvidas ou eventuais desconfianças, contate-nos através das nossas Centrais de Relacionamento. 
• mantenha sempre o navegador e o antivírus atualizados; 
• atualize seus dados pessoais, sempre que houver alguma alteração, através dos nossos canais oficiais de relacionamento; 
• esteja sempre atento às informações constantes nesta política de privacidade e se for cliente, também leia os contratos firmados conosco; 
  

##  Como e quando coletamos seus Dados 
## 
Para conhecermos melhor você e assim oferecermos uma experiência mais adequada, coletamos seus dados desde as suas primeiras interações junto aos nossos canais de relacionamento e/ou stands de venda. 
Em algumas situações você nos fornece seus dados pessoais e em outras eles são obtidos diretamente pela nossa equipe. 
  

##  Você nos fornece seus dados quando: 
## 
• Entra em contato com nossos canais de atendimento, acessa nossos chats, site Cury, plataformas digitais ou ingressa em um dos nossos stands de vendas 
• Utiliza ou contrata algum de nossos produtos; 
• A Cury entra em contato com você. 
  

##  Nós coletamos os seus dados quando: 
## 
• Entra em contato com nossos canais de atendimento, acessa nossos chats, site Cury, plataformas digitais ou ingressa em um dos nossos stands de vendas 
  

## Utilização dos Dados Pessoais por terceiros
## 
Quando necessário para viabilizar a comercialização e manutenção de um produto adquirido por você, nós podemos compartilhar seus dados pessoais com outras empresas, tais como agentes financiadores, empresas responsáveis por análise de crédito, imobiliárias parceiras e empresas terceiras responsáveis por repasses e cobrança e/ou antecipação de pagamentos.
Não compartilhamos seus dados pessoais com prestadores de serviços alheios ao objeto de atuação da Cury. Jamais autorizaremos ou liberaremos dados para que terceiros ofereçam quaisquer tipos de serviços além daquilo que fora estritamente contratado por você, ou seja, não fornecemos e não autorizamos que nossos colaboradores e parceiros forneçam dados ou fechem parcerias com empresas de imóveis modulados, empresas de obras em geral e manutenção predial etc.
No entanto, podemos compartilhar seus dados pessoais com órgãos reguladores, órgãos fiscalizadores, outras autoridades e órgãos oficiais ou empresas de auditoria, com o propósito de cumprir a legislação vigente ou atender demandas legais.
Quando compartilhamos dados com terceiros, inclusive com empresas do grupo Cury, são compartilhados apenas os dados necessários ao cumprimento das atividades e de acordo com as salvaguardas e boas práticas.
  

##  Para que utilizamos seus dados 
## 
Na Cury nós utilizamos seus dados pessoais apenas para fins legítimos, lícitos e relacionados com as atividades objeto de atuação, qual seja, Construção, Incorporação e Venda de Unidades Imobiliárias no âmbito do programa MCMV e/ou Casa Verde e Amarela, sempre observando as legislações vigentes e boas práticas de mercado. Dessa forma, buscamos: 
• Oferecer produtos adequados ao seu perfil de consumo por canais próprios ou externos; 
• Melhorar sua satisfação conosco; 
• Proporcionar uma melhor experiência com a Cury; 
• Cumprir com as exigências legais (como: leis, regulamentações e resoluções); 
• Atender as suas necessidades e expectativas como cliente, parceiro, colaborador, acionista; 
• Valorizar o tratamento justo, digno, cortês e equitativo, assegurando o sigilo das informações. 
Nossos processos são constantemente adequados para utilizarmos apenas as informações necessárias. 
Repudiamos e não autorizamos o tratamento de dados para fins discriminatórios ilícitos ou abusivos. 
Disseminamos em toda a organização a cultura de sigilo, privacidade e proteção dos dados por meio de programa permanente de conscientização e capacitação. 
Adotamos processos e políticas internas que asseguram o cumprimento de normas e boas práticas relativas à proteção de dados pessoais.
  

## Encarregado de Proteção de Dados Pessoais Cury:
## 
Nome do Encarregado: Peck Advogados
Encarregada Titular: Cecília Helena de Castro
Encarregado Substituto: Henrique Rocha
  

## Seus direitos enquanto titular de dados pessoais
## 
  * •Confirmação se nós tratamos algum dado pessoal seu;
  * •Acesso aos seus dados pessoais;
  * •Correção de dados incompletos, inexatos ou desatualizados;
  * •Anonimização, bloqueio ou eliminação de dados desnecessários, excessivos ou tratados em desconformidade com a LGPD;
  * •Portabilidade dos dados a outro fornecedor do mesmo ramo;
  * •Eliminação dos dados pessoais tratados com base no consentimento do titular;
  * •Informação das entidades públicas e privadas com as quais houve compartilhamento de dados;
  * •Não fornecer ou revogar seu consentimento e informação sobre as consequências dessa escolha, se aplicável;
  * •Oposição a tratamento de dados em caso de descumprimento da LGPD.


  

## Em caso de Dúvidas
## 
_Em caso de qualquer dúvida em relação às disposições desta Política, inclusive para entrar em contato com o Encarregado ou exercer quaisquer dos direitos previstos na LGPD, preencha aqui sua solicitação_Formulário LGPD _._
_Podemos alterar esta Política a qualquer momento, por isso recomendamos que você nos visite de vez em quando._
  

Fechar
asdasd dasdsadsa asddsadsa asdadsdas saddasdsaasd
Aceito receber contato por telefone
Aceito receber contato por SMS
Aceito receber contato por WhatsApp
Aceito receber contato por e-mail
Caso o download não seja iniciado automaticamente, clique aqui para baixar o arquivo.
Utilizamos cookies essenciais e tecnologias semelhantes e, ao continuar navegando, você concorda com estas condições.
Para mais informações, confira nossa Política de Privacidade e Política de cookies
OK
##### Sobre
  * Conheça a Cury
  * Regiões
  * Área do Cliente


##### Vendas
  * Imóveis
  * Simular Financiamento
  * Fale com um Corretor


##### Comunicação
  * Contato
  * Assessoria de Imprensa
  * Relações com Investidores


##### Cury nas redes
* * *
* * *
Cury Construtora e Incorporadora S/A 2025 - CRECI 24719-J. Todos os direitos reservados. 
Confira a nossa Política de Privacidade e Política de cookies
Ok
Ofereça seu terreno 
Quero vender meu terreno em: 
São Paulo Rio de Janeiro
Envie um e-mail para adefinir@cury.net com seu **nome** , **telefone** , **área do terreno** e **localização**. 
Ou se preferir, clique aqui   
para cadastrar o seu terreno 
Assessoria de Imprensa 
E-mail: cury@maquinacohnwolfe.com 
; 
Ok
### Control your privacy
AdOpt
Our website uses cookies to improve navigation. Privacy Policy - Terms of use Developed by AdOpt
Customize Reject Accept


# Liens externes trouvés
- https://cury.gupy.io/
- http://www.relacionamentocury.com.br/
- https://api.whatsapp.com/send?phone=5511943136101&text=Olá! Tenho interesse em saber mais sobre a Cury Construtora SP
- https://cury.woxdata.com.br/
- https://canal.ouvidordigital.com.br/curylgpd
- https://www.facebook.com/CuryConstrutora?fref=ts
- https://www.instagram.com/curyconstrutora/
- https://twitter.com/curyconstrutora
- https://www.youtube.com/user/curyconstrutora
- https://www.linkedin.com/company/cury-construtora/
- https://br.pinterest.com/curyconstrutoranet/
- https://www.tiktok.com/@curyconstrutora
- https://open.spotify.com/user/7ibqq6hybxooqerqc8ywnhqe9?si=5WTqJRxfRo6-3RoYe20vYA&nd=1
- adefinir@cury.net
- https://goadopt.io/en/porque-aviso/?utm_content=main&utm_medium=cookie_banner_web&utm_source=cookie_banner_d44972e9-1283-4d1b-b2de-6c0653a2c941
- https://hub.goadopt.io/document/2d556213-4359-44cf-a319-278f1de4e405
- https://hub.goadopt.io/document/b059c8cf-5787-49fc-9c2a-d24fd98d1b2f
  * Imóveis 
  * Cury 
  * Serviços 
  * Área do Cliente
  * São Paulo


  * São Paulo  Rio de Janeiro 


  * Imóveis 
Cury
  * Serviços
  *   * Área do Cliente 


## Quem Somos
## 
A Cury S/A e suas SPEs, as chamadas Sociedades de Propósito Específico, são responsáveis pela incorporação e construção de empreendimentos residenciais nos Estados de São Paulo e Rio de Janeiro, em especial no âmbito do programa Minha Casa Minha Vida e/ou Casa Verde e Amarela. Nossas empresas fazem uso compartilhado de estrutura e recursos, incluindo tecnologia e sistemas. Por conta disso, para fins desta Política de Privacidade, você deve considerar não só a Cury como controladora dos seus dados pessoais, mas também as empresas que fazem parte do nosso grupo empresarial, de acordo com o empreendimento desejado e/ou adquirido. 
Diante disso, temos a responsabilidade de preservar seus dados pessoais e a sua privacidade. Agora, para que você conheça melhor como seus dados pessoais são armazenados e tratados por nós, apresentamos esta Política de Privacidade (Doravante “política”). 
  

## Para quem se aplica
## 
Essa política é para você. Seja um cliente, colaborador, usuário, fornecedor, acionista ou pessoa que se relaciona com a Cury. Se está apenas visitando nosso site para conhecer nossos empreendimentos, essa política também se aplica a você. 
  

## Privacidade e Proteção dos Dados
## 
A sua privacidade e o sigilo de suas informações são muito importantes para nós. Quando você nos procura, utiliza nossos serviços ou adquire nossos produtos, tomamos os cuidados possíveis e necessários para garantir a proteção de seus dados pessoais, o sigilo e o uso adequado. 
A Cury adota as melhores práticas de segurança para garantir a integridade e a confidencialidade dos dados coletados, adotando mecanismos de proteção contra uso indevido, tentativas de acesso não autorizados, fraudes, danos, sabotagens e roubos. 
  

##  Fique Atento 
## 
Para que possamos garantir o sigilo e proteção dos seus dados pessoais, é importante que você também tome os seguintes cuidados: 
• utilize apenas os canais oficiais disponibilizados pela Cury; 
• atente-se para a origem das mensagens, não acessando o nosso site por meio de links recebidos por e-mail, SMS, WhatsApp, Telegram e outros de fontes que não seja da própria Cury e suas empresas coligadas, sendo que em caso de dúvidas ou eventuais desconfianças, contate-nos através das nossas Centrais de Relacionamento. 
• mantenha sempre o navegador e o antivírus atualizados; 
• atualize seus dados pessoais, sempre que houver alguma alteração, através dos nossos canais oficiais de relacionamento; 
• esteja sempre atento às informações constantes nesta política de privacidade e se for cliente, também leia os contratos firmados conosco; 
  

##  Como e quando coletamos seus Dados 
## 
Para conhecermos melhor você e assim oferecermos uma experiência mais adequada, coletamos seus dados desde as suas primeiras interações junto aos nossos canais de relacionamento e/ou stands de venda. 
Em algumas situações você nos fornece seus dados pessoais e em outras eles são obtidos diretamente pela nossa equipe. 
  

##  Você nos fornece seus dados quando: 
## 
• entra em contato com nossos canais de atendimento, acessa nossos chats, site Cury, plataformas digitais ou ingressa em um dos nossos stands de vendas 
• utiliza ou contrata algum de nossos produtos; 
• a Cury entra em contato com você. 
  

##  Nós coletamos os seus dados quando: 
## 
• entra em contato com nossos canais de atendimento, acessa nossos chats, site Cury, plataformas digitais ou ingressa em um dos nossos stands de vendas 
  

##  Para que utilizamos seus dados 
## 
Na Cury nós utilizamos seus dados pessoais apenas para fins legítimos, lícitos e relacionados com as atividades objeto de atuação, qual seja, Construção, Incorporação e Venda de Unidades Imobiliárias no âmbito do programa MCMV e/ou Casa Verde e Amarela, sempre observando as legislações vigentes e boas práticas de mercado. Dessa forma, buscamos: 
• oferecer produtos adequados ao seu perfil de consumo por canais próprios ou externos; 
• melhorar sua satisfação conosco; 
• proporcionar uma melhor experiência com a Cury; 
• cumprir com as exigências legais (como: leis, regulamentações e resoluções); 
• atender as suas necessidades e expectativas como cliente, parceiro, colaborador, acionista; 
• valorizar o tratamento justo, digno, cortês e equitativo, assegurando o sigilo das informações. 
Nossos processos são constantemente adequados para utilizarmos apenas as informações necessárias. 
Repudiamos e não autorizamos o tratamento de dados para fins discriminatórios ilícitos ou abusivos. 
Disseminamos em toda a organização a cultura de sigilo, privacidade e proteção dos dados por meio de programa permanente de conscientização e capacitação. 
Adotamos processos e políticas internas que asseguram o cumprimento de normas e boas práticas relativas à proteção de dados pessoais. 
  

## Deseja informações sobre seus dados pessoais armazenados pela Cury?
## 
Consulte aqui e daremos todas as informações necessárias.
  

## Utilização dos Dados Pessoais por terceiros
## 
Quando necessário para viabilizar a comercialização e manutenção de um produto adquirido por você, nós podemos compartilhar seus dados pessoais com outras empresas, tais como agentes financiadores, empresas responsáveis por análise de crédito, imobiliárias parceiras e empresas terceiras responsáveis por repasses e cobrança e/ou antecipação de pagamentos.
Não compartilhamos seus dados pessoais com prestadores de serviços alheios ao objeto de atuação da Cury. Jamais autorizaremos ou liberaremos dados para que terceiros ofereçam quaisquer tipos de serviços além daquilo que fora estritamente contratado por você, ou seja, não fornecemos e não autorizamos que nossos colaboradores e parceiros forneçam dados ou fechem parcerias com empresas de imóveis modulados, empresas de obras em geral e manutenção predial etc.
No entanto, podemos compartilhar seus dados pessoais com órgãos reguladores, órgãos fiscalizadores, outras autoridades e órgãos oficiais ou empresas de auditoria, com o propósito de cumprir a legislação vigente ou atender demandas legais.
Quando compartilhamos dados com terceiros, inclusive com empresas do grupo Cury, são compartilhados apenas os dados necessários ao cumprimento das atividades e de acordo com as salvaguardas e boas práticas.
  

##  Agradecimento 
## 
Agradecemos por ter lido a nossa política de privacidade e proteção de dados. Ela foi elaborada com o objetivo de ser a mais útil, transparente e simples possível. 
Nossa intenção é assegurar o respeito aos seus interesses e manter um relacionamento ético, responsável e diligente com você. 
Estamos à disposição para esclarecer eventuais dúvidas por meio dos nossos canais de relacionamento ou através do Canal de Incidentes LGPD Cury LGPD.
Pedimos ainda que nos visite de vez em quando, pois quando necessário publicaremos atualizações desta Política. Obrigado! 
  

Fechar
asdasd dasdsadsa asddsadsa asdadsdas saddasdsaasd
Aceito receber contato por telefone
Aceito receber contato por SMS
Aceito receber contato por WhatsApp
Aceito receber contato por e-mail
Caso o download não seja iniciado automaticamente, clique aqui para baixar o arquivo.
Utilizamos cookies essenciais e tecnologias semelhantes e, ao continuar navegando, você concorda com estas condições.
Para mais informações, confira nossa Política de Privacidade e Política de cookies
OK
##### Sobre
  * Conheça a Cury
  * Regiões
  * Área do Cliente


##### Vendas
  * Imóveis
  * Simular Financiamento
  * Fale com um Corretor


##### Comunicação
  * Contato
  * Assessoria de Imprensa
  * Relações com Investidores


##### Cury nas redes
* * *
* * *
Cury Construtora e Incorporadora S/A 2025 - CRECI 24719-J. Todos os direitos reservados. 
Confira a nossa Política de Privacidade e Política de cookies
Ok
Ofereça seu terreno 
Quero vender meu terreno em: 
São Paulo Rio de Janeiro
Envie um e-mail para adefinir@cury.net com seu **nome** , **telefone** , **área do terreno** e **localização**. 
Ou se preferir, clique aqui   
para cadastrar o seu terreno 
Assessoria de Imprensa 
E-mail: cury@maquinacohnwolfe.com 
; 
Ok
### Control your privacy
AdOpt
Our website uses cookies to improve navigation. Privacy Policy - Terms of use Developed by AdOpt
Customize Reject Accept


# Liens externes trouvés
- https://cury.gupy.io/
- http://www.relacionamentocury.com.br/
- https://api.whatsapp.com/send?phone=5521999923476&text=Olá! Tenho interesse em saber mais sobre a Cury Construtora SP
- https://cury.woxdata.com.br/
- https://canal.ouvidordigital.com.br/curylgpd
- https://www.facebook.com/CuryConstrutora?fref=ts
- https://www.instagram.com/curyconstrutora/
- https://twitter.com/curyconstrutora
- https://www.youtube.com/user/curyconstrutora
- https://www.linkedin.com/company/cury-construtora/
- https://br.pinterest.com/curyconstrutoranet/
- https://www.tiktok.com/@curyconstrutora
- https://open.spotify.com/user/7ibqq6hybxooqerqc8ywnhqe9?si=5WTqJRxfRo6-3RoYe20vYA&nd=1
- adefinir@cury.net
- https://goadopt.io/en/porque-aviso/?utm_content=main&utm_medium=cookie_banner_web&utm_source=cookie_banner_d44972e9-1283-4d1b-b2de-6c0653a2c941
- https://hub.goadopt.io/document/2d556213-4359-44cf-a319-278f1de4e405
- https://hub.goadopt.io/document/b059c8cf-5787-49fc-9c2a-d24fd98d1b2f
  * Imóveis 
  * Cury 
  * Serviços 
  * Área do Cliente
  * São Paulo


  * São Paulo  Rio de Janeiro 


  * Imóveis 
Cury
  * Serviços
  *   * Área do Cliente 


Voltar
## Análise de crédito
A Cury Construtora e Incorporadora S.A. (“Cury”) zela pela transparência de seus relacionamentos, ciente da importância que seus Dados Pessoais (assim consideradas informações que sejam capazes de identificar uma pessoa natural ou torná-la identificável), bem como respeitando os preceitos estabelecidos na legislação vigente, em especial, a Lei 13.709/18 (“LGPD” ou “Lei Geral de Proteção de Dados”), explica a você, de forma detalhada, para que utilizará cada uma das informações abaixo.   
  
Lembre-se, você não é obrigado a compartilhar suas informações com a Cury, no entanto é possível que caso os Dados Pessoais indicados como essenciais (abaixo, destacados com o símbolo “*”) não sejam informados, o estabelecimento ou manutenção de um relacionamento com você fique prejudicado.   
  
Você pode obter mais informações sobre as diretrizes que adotamos para o tratamento de Dados Pessoais em nossa Política de Privacidade, disponível na aba “Política de Privacidade” de nosso site. Além disso, nosso encarregado está à sua disposição através do Canal de Incidentes LGPD Cury LGPD.   
  
Ao avançar, eu autorizo, nos termos da Resolução CMN n° 3.658, de 17.12.2008, as instituições financeiras a consultarem as informações consolidadas relativas a minha pessoa, constantes no Sistema de Informações de Créditos (SCR) do BACEN. Autorizo, ainda, as instituições financeiras a fornecerem informações sobre operações de crédito com ela realizadas, no sentido de compor o cadastro do já citado Sistema. Os presentes dados são verdadeiros e visam facilitar os processos de negociação e transações comerciais, pela antecipação de informações a meu respeito. Autorizo o arquivamento dos meus dados pessoais e de idoneidade na SERASA – Centralização de Serviços dos Bancos S/A, que poderá deles se utilizar, respeitadas as disposições legais em vigor. Tenho ciência que as informações aqui dispostas poderão ser utilizadas para possível aprovação de crédito nas instituições financeiras.   
  
Para solicitação de exclusão de dados, acesse https://cury.woxdata.com.br.
Digite seu e-mail Continuar
Enviamos um e-mail para o endereço **xxxxxxxx@xxxxxx.com**.   
Favor clicar no link enviado para dar continuidade ao processo de análise de crédito.
Utilizamos cookies essenciais e tecnologias semelhantes e, ao continuar navegando, você concorda com estas condições.
Para mais informações, confira nossa Política de Privacidade e Política de cookies
OK
##### Sobre
  * Conheça a Cury
  * Regiões
  * Área do Cliente


##### Vendas
  * Imóveis
  * Simular Financiamento
  * Fale com um Corretor


##### Comunicação
  * Contato
  * Assessoria de Imprensa
  * Relações com Investidores


##### Cury nas redes
* * *
* * *
Cury Construtora e Incorporadora S/A 2025 - CRECI 24719-J. Todos os direitos reservados. 
Confira a nossa Política de Privacidade e Política de cookies
Ok
Ofereça seu terreno 
Quero vender meu terreno em: 
São Paulo Rio de Janeiro
Envie um e-mail para adefinir@cury.net com seu **nome** , **telefone** , **área do terreno** e **localização**. 
Ou se preferir, clique aqui   
para cadastrar o seu terreno 
Assessoria de Imprensa 
E-mail: cury@maquinacohnwolfe.com 
; 
Ok
### Control your privacy
AdOpt
Our website uses cookies to improve navigation. Privacy Policy - Terms of use Developed by AdOpt
Customize Reject Accept


# Liens externes trouvés
- https://cury.gupy.io/
- http://www.relacionamentocury.com.br/
- https://api.whatsapp.com/send?phone=5521999923476&text=Olá! Tenho interesse em saber mais sobre a Cury Construtora SP
- javascript:history.back();
- https://canal.ouvidordigital.com.br/curylgpd
- https://cury.woxdata.com.br
- https://www.facebook.com/CuryConstrutora?fref=ts
- https://www.instagram.com/curyconstrutora/
- https://twitter.com/curyconstrutora
- https://www.youtube.com/user/curyconstrutora
- https://www.linkedin.com/company/cury-construtora/
- https://br.pinterest.com/curyconstrutoranet/
- https://www.tiktok.com/@curyconstrutora
- https://open.spotify.com/user/7ibqq6hybxooqerqc8ywnhqe9?si=5WTqJRxfRo6-3RoYe20vYA&nd=1
- adefinir@cury.net
- https://goadopt.io/en/porque-aviso/?utm_content=main&utm_medium=cookie_banner_web&utm_source=cookie_banner_d44972e9-1283-4d1b-b2de-6c0653a2c941
- https://hub.goadopt.io/document/2d556213-4359-44cf-a319-278f1de4e405
- https://hub.goadopt.io/document/b059c8cf-5787-49fc-9c2a-d24fd98d1b2f
  * Imóveis 
  * Cury 
  * Serviços 
  * Área do Cliente
  * São Paulo


  * São Paulo  Rio de Janeiro 


  * Imóveis 
Cury
  * Serviços
  *   * Área do Cliente 


#### Encontre seu imóvel
Estado São Paulo Rio de Janeiro Região Campinas Centro Guarulhos Interior Litoral Santo André Suzano Taboão da Serra Zona Leste Zona Norte Zona Oeste Zona Sul Dormitórios Studio 1 dormitório 2 dormitórios 3 dormitórios
####  Destaques em São Paulo 
Lançamento
#### Supreme Anália Franco
Anália Franco
2 dorms. com opção de suíte | terraço | vaga | lazer completo
Piscinas
Solário
Goumert
Espaço Beleza
Lançamento
#### My Sacomã
Sacomã
2 dorms. com opção de terraço | lazer supreendente
Salão de Festas
Fitness
Praça
Lounge de Jogos
Lançamento
#### 360° Park View
City América
2 dorms. com opção de suíte | terraço | lazer completo
Piscinas
Solário
Piquinique
Sport Bar
Lançamento
#### Galleria Santa Marina
Água Branca
2 dorms. com opção de suíte | terraço | lazer completo com rooftop
Redário
Piscina
Solário
Espaço Goumert
Lançamento
#### Modern Mooca
Mooca
2 e 3 dorms. com opção de suíte | varanda | lazer completo
Rooftop
Fitness
Piscinas
Espaço Beleza
Lançamento
#### Mirae Bom Retiro
Bom Retiro
2 dorms. com opção de terraço | suítes | lazer surpreendente | rooftop.
Lounge Luau
Quadra de Grama Artificial
Churrasqueira Gourmet
Espaço Fitness
Lançamento
#### Cidade Villa Lobos - Maestro
Jaguaré
2 dorms. com opção de terraço | suíte | lazer completo
Piscinas
Churrasqueira
Espaço Fitness
Espaço Beleza
Lançamento
#### The One Granja Julieta
Granja Julieta
2 dorms. com opção de varanda | suíte | lazer completo com rooftop
Piscinas
Fitness
Churrasqueiras
Espaço Goumert
Lançamento
#### Like Campo Limpo
Campo Limpo
2 e 3 dorms. com opção de suíte| terraço | vaga | lazer no rooftop
Rooftop
Piscinas
Espaço Yoga
Espaço Goumert
Lançamento
#### Arte Santa Marina
Água Branca
2 dorms. com opção de suíte | Terraço | Lazer surpreendente no rooftop
Cine
Solário
Churrasqueira
Rooftop
Lançamento
#### The One Chácara Santo Antônio
Chácara Santo Antônio
2 dorms. com opção de varanda | Suíte | Lazer completo
Beach Tennis
Solário
Churrasqueiras
Piscinas
Lançamento
#### Mérito Guarulhos
Ponte Grande
2 dorms. com opção de garden | terraço | lazer completo
Churrasqueira
Piscinas
Beach Tênis
Piquenique
Lançamento
#### Supreme Anália Franco
Anália Franco
2 dorms. com opção de suíte | terraço | vaga | lazer completo
Piscinas
Solário
Goumert
Espaço Beleza
Lançamento
#### My Sacomã
Sacomã
2 dorms. com opção de terraço | lazer supreendente
Salão de Festas
Fitness
Praça
Lounge de Jogos
Lançamento
#### 360° Park View
City América
2 dorms. com opção de suíte | terraço | lazer completo
Piscinas
Solário
Piquinique
Sport Bar
Lançamento
#### Galleria Santa Marina
Água Branca
2 dorms. com opção de suíte | terraço | lazer completo com rooftop
Redário
Piscina
Solário
Espaço Goumert
Lançamento
#### Modern Mooca
Mooca
2 e 3 dorms. com opção de suíte | varanda | lazer completo
Rooftop
Fitness
Piscinas
Espaço Beleza
Lançamento
#### Mirae Bom Retiro
Bom Retiro
2 dorms. com opção de terraço | suítes | lazer surpreendente | rooftop.
Lounge Luau
Quadra de Grama Artificial
Churrasqueira Gourmet
Espaço Fitness
Lançamento
#### Cidade Villa Lobos - Maestro
Jaguaré
2 dorms. com opção de terraço | suíte | lazer completo
Piscinas
Churrasqueira
Espaço Fitness
Espaço Beleza
Lançamento
#### The One Granja Julieta
Granja Julieta
2 dorms. com opção de varanda | suíte | lazer completo com rooftop
Piscinas
Fitness
Churrasqueiras
Espaço Goumert
Lançamento
#### Like Campo Limpo
Campo Limpo
2 e 3 dorms. com opção de suíte| terraço | vaga | lazer no rooftop
Rooftop
Piscinas
Espaço Yoga
Espaço Goumert
Lançamento
#### Arte Santa Marina
Água Branca
2 dorms. com opção de suíte | Terraço | Lazer surpreendente no rooftop
Cine
Solário
Churrasqueira
Rooftop
Lançamento
#### The One Chácara Santo Antônio
Chácara Santo Antônio
2 dorms. com opção de varanda | Suíte | Lazer completo
Beach Tennis
Solário
Churrasqueiras
Piscinas
Lançamento
#### Mérito Guarulhos
Ponte Grande
2 dorms. com opção de garden | terraço | lazer completo
Churrasqueira
Piscinas
Beach Tênis
Piquenique
Lançamento
#### Supreme Anália Franco
Anália Franco
2 dorms. com opção de suíte | terraço | vaga | lazer completo
Piscinas
Solário
Goumert
Espaço Beleza
Lançamento
#### My Sacomã
Sacomã
2 dorms. com opção de terraço | lazer supreendente
Salão de Festas
Fitness
Praça
Lounge de Jogos
Lançamento
#### 360° Park View
City América
2 dorms. com opção de suíte | terraço | lazer completo
Piscinas
Solário
Piquinique
Sport Bar
  * 1
  * 2
  * 3
  * 4


####  Imóveis com a qualidade Cury 
A Cury Construtora iniciou sua história em 7 de maio de 1963 e desde o início tem o objetivo de buscar sempre melhorias e inovações constantes. 
Saiba mais 
#### Faça uma simulação
Quer uma rápida previsão de como pagar seu imóvel? Faça uma simulação:
Iniciar simulação
Utilizamos cookies essenciais e tecnologias semelhantes e, ao continuar navegando, você concorda com estas condições.
Para mais informações, confira nossa Política de Privacidade e Política de cookies
OK
##### Sobre
  * Conheça a Cury
  * Regiões
  * Área do Cliente


##### Vendas
  * Imóveis
  * Simular Financiamento
  * Fale com um Corretor


##### Comunicação
  * Contato
  * Assessoria de Imprensa
  * Relações com Investidores


##### Cury nas redes
* * *
* * *
Cury Construtora e Incorporadora S/A 2025 - CRECI 24719-J. Todos os direitos reservados. 
Confira a nossa Política de Privacidade e Política de cookies
Ok
Ofereça seu terreno 
Quero vender meu terreno em: 
São Paulo Rio de Janeiro
Envie um e-mail para adefinir@cury.net com seu **nome** , **telefone** , **área do terreno** e **localização**. 
Ou se preferir, clique aqui   
para cadastrar o seu terreno 
Assessoria de Imprensa 
E-mail: cury@maquinacohnwolfe.com 
; 
Ok
### Control your privacy
AdOpt
Our website uses cookies to improve navigation. Privacy Policy - Terms of use Developed by AdOpt
Customize Reject Accept


# Liens externes trouvés
- https://cury.gupy.io/
- http://www.relacionamentocury.com.br/
- https://api.whatsapp.com/send?phone=5511943136101&text=Olá! Tenho interesse em saber mais sobre a Cury Construtora SP
- https://www.facebook.com/CuryConstrutora?fref=ts
- https://www.instagram.com/curyconstrutora/
- https://twitter.com/curyconstrutora
- https://www.youtube.com/user/curyconstrutora
- https://www.linkedin.com/company/cury-construtora/
- https://br.pinterest.com/curyconstrutoranet/
- https://www.tiktok.com/@curyconstrutora
- https://open.spotify.com/user/7ibqq6hybxooqerqc8ywnhqe9?si=5WTqJRxfRo6-3RoYe20vYA&nd=1
- adefinir@cury.net
- https://goadopt.io/en/porque-aviso/?utm_content=main&utm_medium=cookie_banner_web&utm_source=cookie_banner_d44972e9-1283-4d1b-b2de-6c0653a2c941
- https://hub.goadopt.io/document/2d556213-4359-44cf-a319-278f1de4e405
- https://hub.goadopt.io/document/b059c8cf-5787-49fc-9c2a-d24fd98d1b2f
  * Imóveis 
  * Cury 
  * Serviços 
  * Área do Cliente
  * São Paulo


  * São Paulo  Rio de Janeiro 


  * Imóveis 
Cury
  * Serviços
  *   * Área do Cliente 


Pronto para Morar
Bom Retiro
### Cury Dez Bom Retiro
1 dorm. , 2 dorms. 
Fale com um corretor
Fale com um corretor 
  * Sobre o imóvel
* * *
  * Diferenciais
* * *
  * Mapa
* * *


Fale com um corretor 
  * Sobre o imóvel
* * *
  * Imagens
* * *
  * Diferenciais
* * *
  * Mapa
* * *


VOCÊ NO CENTRO DE TUDO. PRÓXIMO AO QUE VOCÊ PRECISA. PERTO DO QUE SUA VIDA GOSTA.
Um lugar onde as coisas giram ao redor do seu dia a dia. Esse é o Dez Bom Retiro, o seu novo lar. Agora, sua vida ganha ainda mais possibilidades, facilidades, serviços e entretenimento. Tudo isso, de ponta a ponta, e claro: a poucos metros de casa.
#### Imagens
  * Plantas


  *   *   * 

  *   *   * 

Áreas comuns
#### Diferenciais
  * Fitness externo
  * Churrasqueiras
  * Espaço zen
  * Pet place
  * Playground
  * Praça
  * Salão de Festas
  * Pergolado Jogos
  * Playbaby

Ver todos
Pronto para Morar
Fitness externo
Churrasqueiras
Espaço zen
Fale com um corretor
×
#### Localização
Empreendimento
#### Rua Afonso Pena - Esquina com Rua Salvador Leme, 560, Bom Retiro. SP
Veja como chegar
Waze Google Maps
Clique para exibir o mapa
Rua Afonso Pena - Esquina com Rua Salvador Leme , 560 - Bom Retiro 
#### Sobre a região
Morar no **centro de São Paulo** é a escolha ideal para quem quer estar perto dos principais pontos turísticos e comerciais da cidade. Além de contar com diversidade em **cultura e entretenimento** , a região tem uma variedade de **comércios** que funcionam 24h. Bom Retiro, Bela Vista, Cambuci, Sé e Santa Cecília estão entre os principais distritos centrais.
Comprar imóvel no centro de São Paulo, sem dúvidas, é poder viver em meio à **agitação da vida urbana** enquanto é possível experienciar **passeios históricos** que fizeram com que a cidade tivesse a infraestrutura que tem hoje.
####  Imóveis relacionados 
Em breve
#### Ar.que
Vila Buarques
Teste
Piscina Adulto com Cascata
Churrasqueira
Pronto para Morar
#### Cury Dez Bom Retiro 2
Bom Retiro
2 Dorms com Amplo Lazer
Fitness externo
Churrasqueira
Pet place
Salão de festas
Em breve
#### Square Panamby Itapaiuna
Panamby
Square Panamby Itapaiuna
CCISA 42 incorporadora ltda. Condomínio residencial dez bom retiro. Incorporação registrada em 03/10/2017, r.2 da matrícula 191.613 do 8º oficial de registro de imóveis de São Paulo. Creci SP 23670-J - Responsável Técnico Ronaldo Cury de Capua 
* * *
Utilizamos cookies essenciais e tecnologias semelhantes e, ao continuar navegando, você concorda com estas condições.
Para mais informações, confira nossa Política de Privacidade e Política de cookies
OK
##### Sobre
  * Conheça a Cury
  * Regiões
  * Área do Cliente


##### Vendas
  * Imóveis
  * Simular Financiamento
  * Fale com um Corretor


##### Comunicação
  * Contato
  * Assessoria de Imprensa
  * Relações com Investidores


##### Cury nas redes
* * *
* * *
Cury Construtora e Incorporadora S/A 2025 - CRECI 24719-J. Todos os direitos reservados. 
Confira a nossa Política de Privacidade e Política de cookies
Ok
Ofereça seu terreno 
Quero vender meu terreno em: 
São Paulo Rio de Janeiro
Envie um e-mail para adefinir@cury.net com seu **nome** , **telefone** , **área do terreno** e **localização**. 
Ou se preferir, clique aqui   
para cadastrar o seu terreno 
Assessoria de Imprensa 
E-mail: cury@maquinacohnwolfe.com 
; 
Ok


# Liens externes trouvés
- https://cury.gupy.io/
- http://www.relacionamentocury.com.br/
- https://api.whatsapp.com/send?phone=5521999923476&text=Olá! Tenho interesse em saber mais sobre o imóvel Cury Dez Bom Retiro.
- https://waze.com/ul?ll=-23.526762,-46.633295&navigate=yes
- https://maps.google.com/maps?daddr=-23.526762,-46.633295
- https://www.facebook.com/CuryConstrutora?fref=ts
- https://www.instagram.com/curyconstrutora/
- https://twitter.com/curyconstrutora
- https://www.youtube.com/user/curyconstrutora
- https://www.linkedin.com/company/cury-construtora/
- https://br.pinterest.com/curyconstrutoranet/
- https://www.tiktok.com/@curyconstrutora
- https://open.spotify.com/user/7ibqq6hybxooqerqc8ywnhqe9?si=5WTqJRxfRo6-3RoYe20vYA&nd=1
- adefinir@cury.net
  * Área do  
cliente
  * Relações com Investidores
  * Encontre sua casa própria 
São Paulo Rio de Janeiro Região Campinas  Centro  Interior  Litoral  Santo André  Zona Leste  Zona lost  Zona Norte  Zona Oeste  Zona Sul  Região Baixada Fluminense  Centro  Niterói  São Gonçalo  Zona Norte  Zona Oeste  Tipo Apartamento Casa Tipo Apartamento Casa Comercial Encontrar Encontrar


###  Selecione o que deseja: 
  * Área do Cliente
  * Conheça a Cury
  * Imóveis
  * Corretor Online
  * Imobiliárias e Corretores
  * TV Cury
  * Área do Cliente
  * Ofereça seu Terreno
  * Análise de Crédito
  * Relações com Investidores
  * Trabalhe Conosco
  * Site RJ
  * Site Campinas
  * Ouvidoria LGPD


  * # Energia elétrica
## Consumo consciente


# Dicas
Todas as categorias Culinária Decoração Brand New Category Bem estar Empreendimentos
  * #### Varandas, um cômodo com 1.001 utilidades
Cômodo quase onipresente nos apartamentos, as varandas oferecem inúmeras utilidades. Receber os amigos e a família, curtir uma música, ler um livro, d...
  * #### Assembleias de condomínio
Essas reuniões normalmente não têm muita aderência dos proprietários, mesmo sendo primordial a presença de todos para o levantamento de questões a ser...
  * #### Quartos para irmãos: Saiba como decorar
Escolher a decoração de quartos de duas ou mais crianças nem sempre é uma tarefa fácil. Manter o equilíbrio para caracterizar o ambiente sem fugir do ...
  * #### Energia elétrica: consumo consciente
É no verão que mais se eleva o consumo de energia elétrica por conta da falta de chuva, do calor excessivo e da utilização intensa dos aparelhos eletr...


Mais dicas
Utilizamos cookies e tecnologias semelhantes de acordo com a nossa Política de Privacidade e, ao continuar navegando, você concorda com estas condições.
OK X
  * Chat online
  * Simule o seu financiamento
  * Telefone:  
(11) 3230-0830 Telefone:  
(11) 3230-0830
  * Whatsapp


  * nosso facebook
  * nosso instagram
  * nosso twitter
  * nosso youtube
  * nosso linkedin
  * nosso pinterest


## Sobre
  * Conheça a Cury
  * Regiões
  * Dicas
  * TV Cury
  * Área Cliente


## Vendas
  * Imóveis
  * Simular financiamento
  * Fale com um corretor


## Comunicação
  * Contato
  * Imobiliárias e Corretores
  * Relate desvio de conduta
  * Relações com Investidores


Cury Construtora e Incorporadora S/A 2025 - CRECI 24719-J.  
Todos os direitos reservados. 
Confira a nossa  Política de Privacidade 
Ok
Fechar
Olá. Deseja receber mais informações sobre nossos empreendimentos? Deixe seus dados e entraremos em contato:
Enviar
  
com sucesso 
  
tente novamente 
Ofereça seu terreno 
Quero vender meu terreno em: 
São Paulo Rio de Janeiro
Envie um e-mail para adefinir@cury.net com seu **nome** , **telefone** , **área do terreno** e **localização**. 
Ou se preferir, clique aqui   
para cadastrar o seu terreno 


# Liens externes trouvés
- http://www.relacionamentocury.com.br/
- https://cury.gupy.io/
- https://canal.ouvidordigital.com.br/curylgpd
- tel:+55-11-3230-0830
- javascript:;
- https://api.whatsapp.com/send?phone=5521999923476&text=Olá! Tenho interesse em saber mais sobre a Cury Construtora SP
- https://www.facebook.com/CuryConstrutora?fref=ts
- https://www.instagram.com/curyconstrutora/
- https://twitter.com/curyconstrutora
- https://www.youtube.com/user/curyconstrutora
- https://www.linkedin.com/company/cury-construtora/
- https://br.pinterest.com/curyconstrutoranet/
- adefinir@cury.net
  * Imóveis 
  * Cury 
  * Serviços 
  * Área do Cliente
  * São Paulo


  * São Paulo  Rio de Janeiro 


  * Imóveis 
Cury
  * Serviços
  *   * Área do Cliente 


Em breve
Panamby
### Cury Square Panamby
Studio 
Fale com um corretor
Fale com um corretor 
  * Sobre o imóvel
* * *


Fale com um corretor 
  * Sobre o imóvel
* * *


Cury Square Panamby  

Em breve
Fale com um corretor
×
#### Sobre a região
**Campinas** é a maior cidade do interior de São Paulo, conhecida também como um dos principais **polos tecnológicos** da América Latina. Atualmente, essa região metropolitana é o **terceiro maior centro industrial do país**.
A apenas 92 km da capital paulista, Campinas tem sido uma das cidades mais desejadas para viver. Comprar apartamento na cidade é ter acesso a uma completa infraestrutura e uma cidade inteligente e conectada.
####  Imóveis relacionados 
Em breve
#### Square Panamby Itapaiuna
Panamby
Square Panamby Itapaiuna
Em Obras
#### Cury Urban Parque das Bandeiras
Campinas
2 Dorms, com terraço e amplo lazer
Fitness
Salão de festas
Churrasqueira
Coworking
Em Obras
#### Cury Dez Parque das Bandeiras
Campinas
2 Dorms com Varanda, Vaga e Lazer Completo
Piscina adulto
Churrasqueira
Fitness
Brinquedoteca
Cury Square Panamby  

* * *
Utilizamos cookies essenciais e tecnologias semelhantes e, ao continuar navegando, você concorda com estas condições.
Para mais informações, confira nossa Política de Privacidade e Política de cookies
OK
##### Sobre
  * Conheça a Cury
  * Regiões
  * Área do Cliente


##### Vendas
  * Imóveis
  * Simular Financiamento
  * Fale com um Corretor


##### Comunicação
  * Contato
  * Assessoria de Imprensa
  * Relações com Investidores


##### Cury nas redes
* * *
* * *
Cury Construtora e Incorporadora S/A 2025 - CRECI 24719-J. Todos os direitos reservados. 
Confira a nossa Política de Privacidade e Política de cookies
Ok
Ofereça seu terreno 
Quero vender meu terreno em: 
São Paulo Rio de Janeiro
Envie um e-mail para adefinir@cury.net com seu **nome** , **telefone** , **área do terreno** e **localização**. 
Ou se preferir, clique aqui   
para cadastrar o seu terreno 
Assessoria de Imprensa 
E-mail: cury@maquinacohnwolfe.com 
; 
Ok
### Control your privacy
AdOpt
Our website uses cookies to improve navigation. Privacy Policy - Terms of use Developed by AdOpt
Customize Reject Accept


# Liens externes trouvés
- https://cury.gupy.io/
- http://www.relacionamentocury.com.br/
- https://api.whatsapp.com/send?phone=5521999923476&text=Olá! Tenho interesse em saber mais sobre o imóvel Cury Square Panamby.
- https://www.facebook.com/CuryConstrutora?fref=ts
- https://www.instagram.com/curyconstrutora/
- https://twitter.com/curyconstrutora
- https://www.youtube.com/user/curyconstrutora
- https://www.linkedin.com/company/cury-construtora/
- https://br.pinterest.com/curyconstrutoranet/
- https://www.tiktok.com/@curyconstrutora
- https://open.spotify.com/user/7ibqq6hybxooqerqc8ywnhqe9?si=5WTqJRxfRo6-3RoYe20vYA&nd=1
- adefinir@cury.net
- https://goadopt.io/en/porque-aviso/?utm_content=main&utm_medium=cookie_banner_web&utm_source=cookie_banner_d44972e9-1283-4d1b-b2de-6c0653a2c941
- https://hub.goadopt.io/document/2d556213-4359-44cf-a319-278f1de4e405
- https://hub.goadopt.io/document/b059c8cf-5787-49fc-9c2a-d24fd98d1b2f
  * Imóveis 
  * Cury 
  * Serviços 
  * Área do Cliente
  * São Paulo


  * São Paulo  Rio de Janeiro 


  * Imóveis 
Cury
  * Serviços
  *   * Área do Cliente 


## Conheça a Cury
Institucional  Ações Porto Maravilha  Instituto Cury  Certificados  Sustentabilidade  Prêmios  Relatório de Igualdade Salarial  Programas Internos  Programas para clientes 
  * Institucional 
  * Ações Porto Maravilha 
  * Instituto Cury 
  * Certificados 
  * Sustentabilidade 
  * Prêmios 
  * Relatório de Igualdade Salarial 
  * Programas Internos 
  * Programas para clientes 


#### Institucional
A Cury iniciou sua história em 7 de maio de 1963 e desde o início tem o objetivo de buscar sempre melhorias e inovações constantes.  
Em 4 de julho de 2007 a Cury passou a ser Cury Construtora e Incorporadora S.A., fruto de uma joint-venture entre Cyrela Brazil Realty e Cury Empreendimentos. Já nascemos com mais de 40 anos de experiência e seguimos possuindo qualidade em nossas obras aliadas ao valor acessível para o nosso público-alvo que se encaixa no programa Minha Casa Minha Vida.  
Além de certificados reconhecidos no mercado, também possuímos diversos prêmios imobiliários no decorrer dos anos.  
Mas o maior reconhecimento está na satisfação de nossos clientes e na realização do sonho de milhares de pessoas que valorizam e usufruem do rigor na escolha dos endereços, do alto padrão de construção, da perfeição do acabamento e do restrito cumprimento dos prazos, princípios que fazem a Cury evoluir e ficar melhor a cada dia.  
Em 2020 realizamos nosso IPO e entramos na B3, a Bolsa de Valores Brasileira. Com mais esse marco histórico, estamos ainda mais focados na nossa missão de reduzir o déficit habitacional e ser a construtora número 1 dos brasileiros.  
  
Confira mais sobre a Cury.
#### Princípios Essenciais
### Missão
Contribuir ativamente para o desenvolvimento sustentável do Brasil, ajudando as pessoas a realizarem o sonho da casa própria, entendendo e respeitando nossos clientes.
### Visão
Ser referência em habitação, sendo reconhecidos por eficiência na construção, tempo hábil de entrega e soluções comerciais e financeiras adequadas aos nossos clientes, pautado na ética, responsabilidade, transparência, competência e solidez.
### Valores
Ética e transparência; Relação companhia-cliente; Resultados para os acionistas; Comprometimento; Dividir o sucesso; Sustentabilidade.
#### Endereços e contatos
**Assessoria de Imprensa**
E-mail: cury@maquinacohnwolfe.com
**São Paulo**
Rua Funchal, 411 - 1º andar Vila Olímpia - São Paulo - SP Telefone: (11) 3117-1300
**Rio de Janeiro**
Rua da Quitanda 86 - 7º andar Centro - Rio de Janeiro/RJ Telefone: (21) 3543-6887
**Cury Vendas SP**
Rua Robert Bosch, 544, Barra Funda - São Paulo/SP Telefone: (11) 3117-1313
**Cury Vendas RJ**
Rua da Quitanda 86 - 7º andar Centro - Rio de Janeiro/RJ Telefone: (21) 3554-3350
**Relacionamento**
Central de Relacionamento: - SP (11) 3117-1300 | - RJ (21) 3543- 6887 e 0800 314 9696 | De segunda-feira a sexta-feira das 09h às 16h.
Utilizamos cookies essenciais e tecnologias semelhantes e, ao continuar navegando, você concorda com estas condições.
Para mais informações, confira nossa Política de Privacidade e Política de cookies
OK
##### Sobre
  * Conheça a Cury
  * Regiões
  * Área do Cliente


##### Vendas
  * Imóveis
  * Simular Financiamento
  * Fale com um Corretor


##### Comunicação
  * Contato
  * Assessoria de Imprensa
  * Relações com Investidores


##### Cury nas redes
* * *
* * *
Cury Construtora e Incorporadora S/A 2025 - CRECI 24719-J. Todos os direitos reservados. 
Confira a nossa Política de Privacidade e Política de cookies
Ok
Ofereça seu terreno 
Quero vender meu terreno em: 
São Paulo Rio de Janeiro
Envie um e-mail para adefinir@cury.net com seu **nome** , **telefone** , **área do terreno** e **localização**. 
Ou se preferir, clique aqui   
para cadastrar o seu terreno 
Assessoria de Imprensa 
E-mail: cury@maquinacohnwolfe.com 
; 
Ok
### Control your privacy
AdOpt
Our website uses cookies to improve navigation. Privacy Policy - Terms of use Developed by AdOpt
Customize Reject Accept


# Liens externes trouvés
- https://cury.gupy.io/
- http://www.relacionamentocury.com.br/
- https://api.whatsapp.com/send?phone=5511943136101&text=Olá! Tenho interesse em saber mais sobre a Cury Construtora SP
- https://www.facebook.com/CuryConstrutora?fref=ts
- https://www.instagram.com/curyconstrutora/
- https://twitter.com/curyconstrutora
- https://www.youtube.com/user/curyconstrutora
- https://www.linkedin.com/company/cury-construtora/
- https://br.pinterest.com/curyconstrutoranet/
- https://www.tiktok.com/@curyconstrutora
- https://open.spotify.com/user/7ibqq6hybxooqerqc8ywnhqe9?si=5WTqJRxfRo6-3RoYe20vYA&nd=1
- adefinir@cury.net
- https://goadopt.io/en/porque-aviso/?utm_content=main&utm_medium=cookie_banner_web&utm_source=cookie_banner_d44972e9-1283-4d1b-b2de-6c0653a2c941
- https://hub.goadopt.io/document/2d556213-4359-44cf-a319-278f1de4e405
- https://hub.goadopt.io/document/b059c8cf-5787-49fc-9c2a-d24fd98d1b2f
  * Imóveis 
  * Cury 
  * Serviços 
  * Área do Cliente
  * São Paulo


  * São Paulo  Rio de Janeiro 


  * Imóveis 
Cury
  * Serviços
  *   * Área do Cliente 


Em breve
Panamby
### Square Panamby Itapaiuna
Studio 
Fale com um corretor
Fale com um corretor 
  * Sobre o imóvel
* * *


Fale com um corretor 
  * Sobre o imóvel
* * *


Square Panamby Itapaiuna  

Em breve
Fale com um corretor
×
#### Sobre a região
**Campinas** é a maior cidade do interior de São Paulo, conhecida também como um dos principais **polos tecnológicos** da América Latina. Atualmente, essa região metropolitana é o **terceiro maior centro industrial do país**.
A apenas 92 km da capital paulista, Campinas tem sido uma das cidades mais desejadas para viver. Comprar apartamento na cidade é ter acesso a uma completa infraestrutura e uma cidade inteligente e conectada.
####  Imóveis relacionados 
Em breve
#### Cury Square Panamby
Panamby
Cury Square Panamby
Em Obras
#### Cury Urban Parque das Bandeiras
Campinas
2 Dorms, com terraço e amplo lazer
Fitness
Salão de festas
Churrasqueira
Coworking
Em Obras
#### Cury Dez Parque das Bandeiras
Campinas
2 Dorms com Varanda, Vaga e Lazer Completo
Piscina adulto
Churrasqueira
Fitness
Brinquedoteca
Square Panamby Itapaiuna  

* * *
Utilizamos cookies essenciais e tecnologias semelhantes e, ao continuar navegando, você concorda com estas condições.
Para mais informações, confira nossa Política de Privacidade e Política de cookies
OK
##### Sobre
  * Conheça a Cury
  * Regiões
  * Área do Cliente


##### Vendas
  * Imóveis
  * Simular Financiamento
  * Fale com um Corretor


##### Comunicação
  * Contato
  * Assessoria de Imprensa
  * Relações com Investidores


##### Cury nas redes
* * *
* * *
Cury Construtora e Incorporadora S/A 2025 - CRECI 24719-J. Todos os direitos reservados. 
Confira a nossa Política de Privacidade e Política de cookies
Ok
Ofereça seu terreno 
Quero vender meu terreno em: 
São Paulo Rio de Janeiro
Envie um e-mail para adefinir@cury.net com seu **nome** , **telefone** , **área do terreno** e **localização**. 
Ou se preferir, clique aqui   
para cadastrar o seu terreno 
Assessoria de Imprensa 
E-mail: cury@maquinacohnwolfe.com 
; 
Ok
### Control your privacy
AdOpt
Our website uses cookies to improve navigation. Privacy Policy - Terms of use Developed by AdOpt
Customize Reject Accept


# Liens externes trouvés
- https://cury.gupy.io/
- http://www.relacionamentocury.com.br/
- https://api.whatsapp.com/send?phone=5521999923476&text=Olá! Tenho interesse em saber mais sobre o imóvel Square Panamby Itapaiuna.
- https://www.facebook.com/CuryConstrutora?fref=ts
- https://www.instagram.com/curyconstrutora/
- https://twitter.com/curyconstrutora
- https://www.youtube.com/user/curyconstrutora
- https://www.linkedin.com/company/cury-construtora/
- https://br.pinterest.com/curyconstrutoranet/
- https://www.tiktok.com/@curyconstrutora
- https://open.spotify.com/user/7ibqq6hybxooqerqc8ywnhqe9?si=5WTqJRxfRo6-3RoYe20vYA&nd=1
- adefinir@cury.net
- https://goadopt.io/en/porque-aviso/?utm_content=main&utm_medium=cookie_banner_web&utm_source=cookie_banner_d44972e9-1283-4d1b-b2de-6c0653a2c941
- https://hub.goadopt.io/document/2d556213-4359-44cf-a319-278f1de4e405
- https://hub.goadopt.io/document/b059c8cf-5787-49fc-9c2a-d24fd98d1b2f
  * Imóveis 
  * Cury 
  * Serviços 
  * Área do Cliente
  * São Paulo


  * São Paulo  Rio de Janeiro 


  * Imóveis 
Cury
  * Serviços
  *   * Área do Cliente 


##   

## Juntos, vamos construir um ambiente de trabalho ainda melhor para todos.
A Cury é uma empresa que tem a verdade e os princípios éticos acima de tudo, buscando fazer o certo nos negócios e nas relações humanas. Isso faz com que ela seja uma das incorporadoras mais admiradas do mercado imobiliário do país.
Para continuar atuando de forma ética, preservando a sua essência, a Cury disponibiliza aos seus colaboradores um canal de comunicação para relato de fatos e condutas que não estejam de acordo com seus princípios, consolidados no Código de Conduta.
Para que o canal seja transparente, o contato deve ser realizado através do endereço https://ouvidordigital.com.br/curyconstrutora. Todos os registros são recebidos e tratados pelo Comitê de Ética, que garante o sigilo absoluto das informações.
Além disso, a Cury possui Política de Tratamento e Gestão de Denúncias para resguardar que as investigações sejam imparciais, com compromisso de promover a ética e a integridade em todas as operações da companhia. Para maiores detalhes, veja a Política na íntegra: Política de Tratamento e Gestão de Denúncias
Para questões relacionadas ao seu contrato e sua unidade, solicitamos que entre em contato com a nossa Central de Relacionamento através do telefone 0800 314 9696 e/ou do endereço https://cury.force.com/portaldocliente/PortalLogin.
Contamos com você para colocar em prática nossas diretrizes de conduta.
  

Baixar código de conduta
##   

##  Cury e Projeto Justiceiras  

##   

A Cury está totalmente engajada na luta contra a violência feminina. Trabalhamos diariamente na construção do sonho de milhares de brasileiros e brasileiras. Nossos empreendimentos são objeto de desejo de pessoas de diferentes faixas etárias e classes sociais. Dessa forma, buscando promover um ambiente social e um ambiente corporativo cada vez mais seguros, em parceria com o “Projeto Justiceiras”, o Programa de Integridade Cury (PIC) disponibiliza um link de comunicação exclusivo e focado na orientação jurídica, psicológica, socioassistencial, médica e toda rede de apoio e acolhimento gratuito para mulheres em situação de vulnerabilidade.  
  

Importante mencionar que o Projeto pode ser acessado por toda e qualquer mulher, sejam elas colaboradoras, prestadoras de serviços ou clientes Cury. Basta clicar no link abaixo e seguir as orientações. Após a análise das informações prestadas pelo(a) denunciante, inicia-se o contato com a vítima através de um grupo profissional e multidisciplinar, com a finalidade de auxiliar na busca dos seus direitos.  
  

Uma vida livre de violência é um direito de toda mulher!  

  

Obtenha ajuda aqui!
Perguntas Frequentes  

  * **Vou ser identificado?**


Não. Caberá a você optar por identificar-se ou não. O contato não compromete o anonimato e você não será identificado.
  

  * **Como devo fazer o contato?**


Você pode relatar um desvio de conduta pelo site https://ouvidordigital.com.br/curyconstrutora.
  

  * **Que situação posso relatar?**


Qualquer comportamento que não esteja de acordo com o Código de Ética da empresa ou que você perceba ser uma atitude incoerente com a esperada de funcionários e parceiros da Cury. São exemplos: fraude, mau uso ou desvio de recursos, discriminação, agressão, abuso de poder etc. Além disso, o canal também pode ser usado para sugestão de melhorias.
  

  * **Preciso ter provas?**


Não. Depois de recebermos o formulário, ele será encaminhado para um comitê que iniciará a análise buscando as informações necessárias para dar o encaminhamento justo à questão. Providências só serão tomadas nos casos em que a conduta incorreta for comprovada.
  

  * **Quais são os benefícios?**


Com o apoio deste canal, a empresa promove a cultura da transparência, alinhando comportamentos e desestimulando condutas contrárias aos seus princípios. Como resultado, temos um ambiente de trabalho cada vez melhor.
  

Fechar
asdasd dasdsadsa asddsadsa asdadsdas saddasdsaasd
Aceito receber contato por telefone
Aceito receber contato por SMS
Aceito receber contato por WhatsApp
Aceito receber contato por e-mail
Caso o download não seja iniciado automaticamente, clique aqui para baixar o arquivo.
Utilizamos cookies essenciais e tecnologias semelhantes e, ao continuar navegando, você concorda com estas condições.
Para mais informações, confira nossa Política de Privacidade e Política de cookies
OK
##### Sobre
  * Conheça a Cury
  * Regiões
  * Área do Cliente


##### Vendas
  * Imóveis
  * Simular Financiamento
  * Fale com um Corretor


##### Comunicação
  * Contato
  * Assessoria de Imprensa
  * Relações com Investidores


##### Cury nas redes
* * *
* * *
Cury Construtora e Incorporadora S/A 2025 - CRECI 24719-J. Todos os direitos reservados. 
Confira a nossa Política de Privacidade e Política de cookies
Ok
Ofereça seu terreno 
Quero vender meu terreno em: 
São Paulo Rio de Janeiro
Envie um e-mail para adefinir@cury.net com seu **nome** , **telefone** , **área do terreno** e **localização**. 
Ou se preferir, clique aqui   
para cadastrar o seu terreno 
Assessoria de Imprensa 
E-mail: cury@maquinacohnwolfe.com 
; 
Ok
### Control your privacy
AdOpt
Our website uses cookies to improve navigation. Privacy Policy - Terms of use Developed by AdOpt
Customize Reject Accept


# Liens externes trouvés
- https://cury.gupy.io/
- http://www.relacionamentocury.com.br/
- https://api.whatsapp.com/send?phone=5511943136101&text=Olá! Tenho interesse em saber mais sobre a Cury Construtora SP
- https://ouvidordigital.com.br/curyconstrutora
- https://firebasestorage.googleapis.com/v0/b/ouvidor-digital-br.appspot.com/o/20b19005-2589-4f43-b8dd-f7700c3d63a9%2Fdocuments%2FCury2025_2%20-%202025-04-14T18%3A36%3A45.663Z?alt=media&token=b92fe94a-a9bb-4a23-9939-f1289cadb539&lang=pt
- https://cury.force.com/portaldocliente/PortalLogin
- https://docs.google.com/forms/d/e/1FAIpQLSft--ccomNpgfVaU0O9Xjpmg_vLmhHsKZ8SG5YiphdMRshpgg/viewform
- https://www.facebook.com/CuryConstrutora?fref=ts
- https://www.instagram.com/curyconstrutora/
- https://twitter.com/curyconstrutora
- https://www.youtube.com/user/curyconstrutora
- https://www.linkedin.com/company/cury-construtora/
- https://br.pinterest.com/curyconstrutoranet/
- https://www.tiktok.com/@curyconstrutora
- https://open.spotify.com/user/7ibqq6hybxooqerqc8ywnhqe9?si=5WTqJRxfRo6-3RoYe20vYA&nd=1
- adefinir@cury.net
- https://goadopt.io/en/porque-aviso/?utm_content=main&utm_medium=cookie_banner_web&utm_source=cookie_banner_d44972e9-1283-4d1b-b2de-6c0653a2c941
- https://hub.goadopt.io/document/2d556213-4359-44cf-a319-278f1de4e405
- https://hub.goadopt.io/document/b059c8cf-5787-49fc-9c2a-d24fd98d1b2f
  * Imóveis 
  * Cury 
  * Serviços 
  * Área do Cliente
  * São Paulo


  * São Paulo  Rio de Janeiro 


  * Imóveis 
Cury
  * Serviços
  *   * Área do Cliente 


Lançamento
Santo André
### Cury Jardim
2 dorms. 
Fale com um corretor
Fale com um corretor 
  * Sobre o imóvel
* * *
{ 
  * Imagens
* * *
  * Diferenciais
* * *
  * Mapa
* * *
  * Obras
* * *


Fale com um corretor 
  * Sobre o imóvel
* * *
  * Imagens
* * *
  * Diferenciais
* * *
  * Mapa
* * *
  * Obras
* * *


**Sua próxima estação é ser feliz! Apartamentos de2 Dorms, com opção de terraço, com ou sem vaga, lazer completo. **
  * 4 Min do Parque Celso Daniel;
  * 5 Min do Grand Plaza Shopping;
  * 7 Min do Sonda Supermercados;
  * 8 Min da Estação Prefeito Celso Daniel Santo André;
  * 8 Min do Carrefour;
  * 13 Min do Centro de Santo André;
  * Fácil acesso às avenidas Industrial e Dom Pedro ||. 


#### Imagens
  * Foto Ilustrativa
  * Plantas
  * Vídeo tour 


  *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   * 

  *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   * 

  *   *   *   * 

  *   *   *   * 

Áreas comuns
#### Diferenciais
  * Piscina Adulto
  * Piscina Infantil
  * Salão de Festas
  * Food Square
  * Cine Open Air
  * Bar Praia
  * Pub e Jogos
  * Quadra em Grama Sintética
  * Espaço Fitness
  * Fitness Externo
  * Bicicletário
  * Coworking
  * Sala Multiuso
  * Easy Market
  * Lavanderia
  * Office Space
  * Espaço Mulher
  * Brinquedoteca
  * Playground
  * Pet Care
  * Pet Place
  * Espaço de Convivência
  * Delivery

Ver todos
Lançamento
Piscina Adulto
Piscina Infantil
Salão de Festas
Fale com um corretor
×
#### Acompanhamento de obras
Mobiliz. Canteiro
100%
Fundação
35%
Estrutura
0%
Alvenaria
75%
Acabamento interno
5%
Acabamento externo
5%
Inst. Elétricas
0%
Inst. Hidráulicas
10%
Pintura
80%
Serv. Complementares
65%
  * Obras4 
  * 

Ver Vídeo
#### Localização
Stand de Vendas
#### Av Brigadeiro Faria Lima, 1740. São Paulo - SP
Veja como chegar
Waze Google Maps
Empreendimento
#### Av Paulista, 688, Cerqueira Cesar. São Paulo - SP
Veja como chegar
Waze Google Maps
Clique para exibir o mapa
Av Paulista , 688 - Cerqueira Cesar 
Av Brigadeiro Faria Lima , 1740 
#### Sobre a região
Com um desenvolvimento pautado na instalação de montadoras de veículos na região, ao longo da década de 60, Santo André começou a despontar economicamente e ser um dos destaques do Estado na geração de empregos, crescendo em ritmo acelerado também em setores como o de peças automotivas, eletrônicos, componentes para refrigeração, dentre outros.
Apesar disso, nos últimos anos, os setores comerciais e de serviços também foram se desenvolvendo e crescendo na cidade, fazendo com que Santo André continuasse com o status de uma das cidades que mais geram empregos em todo o Estado.
####  Imóveis relacionados 
Em Obras
#### Plantão para testes 2
Casa do Will
Texto de destaque
Em breve
#### Square Panamby Itapaiuna
Panamby
Square Panamby Itapaiuna
Em breve
#### Ar.que
Vila Buarques
Teste
Piscina Adulto com Cascata
Churrasqueira
Ccisa69 incorporação ltda (condomínio residencial dez jardim). Incorporação registrada em 15/10/2021, r.05 da matrícula 167.766 do 1º oficial de registro de imóveis de santo andré. Para mais informações, consulte a central de vendas da cury ( cnpj: 14.055.045/0001-78; ccisa 08 consultoria imobiliária ltda. - creci 23670-j). Responsável técnico ronaldo cury de capua.
* * *
Utilizamos cookies essenciais e tecnologias semelhantes e, ao continuar navegando, você concorda com estas condições.
Para mais informações, confira nossa Política de Privacidade e Política de cookies
OK
##### Sobre
  * Conheça a Cury
  * Regiões
  * Área do Cliente


##### Vendas
  * Imóveis
  * Simular Financiamento
  * Fale com um Corretor


##### Comunicação
  * Contato
  * Assessoria de Imprensa
  * Relações com Investidores


##### Cury nas redes
* * *
* * *
Cury Construtora e Incorporadora S/A 2025 - CRECI 24719-J. Todos os direitos reservados. 
Confira a nossa Política de Privacidade e Política de cookies
Ok
Ofereça seu terreno 
Quero vender meu terreno em: 
São Paulo Rio de Janeiro
Envie um e-mail para adefinir@cury.net com seu **nome** , **telefone** , **área do terreno** e **localização**. 
Ou se preferir, clique aqui   
para cadastrar o seu terreno 
Assessoria de Imprensa 
E-mail: cury@maquinacohnwolfe.com 
; 
Ok
### Control your privacy
AdOpt
Our website uses cookies to improve navigation. Privacy Policy - Terms of use Developed by AdOpt
Customize Reject Accept


# Liens externes trouvés
- https://cury.gupy.io/
- http://www.relacionamentocury.com.br/
- https://api.whatsapp.com/send?phone=5521999923476&text=Olá! Tenho interesse em saber mais sobre o imóvel Cury Jardim.
- https://www.youtube.com/watch?v=OUcn9Sq4dvM
- https://waze.com/ul?ll=-23.577328514843717,-46.686788260708404&navigate=yes
- https://maps.google.com/maps?daddr=-23.577328514843717,-46.686788260708404
- https://waze.com/ul?ll=-23.566565732727806,-46.6494593202319&navigate=yes
- https://maps.google.com/maps?daddr=-23.566565732727806,-46.6494593202319
- https://www.facebook.com/CuryConstrutora?fref=ts
- https://www.instagram.com/curyconstrutora/
- https://twitter.com/curyconstrutora
- https://www.youtube.com/user/curyconstrutora
- https://www.linkedin.com/company/cury-construtora/
- https://br.pinterest.com/curyconstrutoranet/
- https://www.tiktok.com/@curyconstrutora
- https://open.spotify.com/user/7ibqq6hybxooqerqc8ywnhqe9?si=5WTqJRxfRo6-3RoYe20vYA&nd=1
- adefinir@cury.net
- https://goadopt.io/en/porque-aviso/?utm_content=main&utm_medium=cookie_banner_web&utm_source=cookie_banner_d44972e9-1283-4d1b-b2de-6c0653a2c941
- https://hub.goadopt.io/document/2d556213-4359-44cf-a319-278f1de4e405
- https://hub.goadopt.io/document/b059c8cf-5787-49fc-9c2a-d24fd98d1b2f
  * Imóveis 
  * Cury 
  * Serviços 
  * Área do Cliente
  * São Paulo 


  * São Paulo  Rio de Janeiro 


  * Imóveis 
Cury
  * Serviços
  *   * Área do Cliente 


Lançamento
Santo André
### Cury Jardim
2 dorms. 
Fale com um corretor
Fale com um corretor 
  * Sobre o imóvel
* * *
{ 
  * Imagens
* * *
  * Diferenciais
* * *
  * Mapa
* * *
  * Obras
* * *


Fale com um corretor 
  * Sobre o imóvel
* * *
  * Imagens
* * *
  * Diferenciais
* * *
  * Mapa
* * *
  * Obras
* * *


**Sua próxima estação é ser feliz! Apartamentos de2 Dorms, com opção de terraço, com ou sem vaga, lazer completo. **
  * 4 Min do Parque Celso Daniel;
  * 5 Min do Grand Plaza Shopping;
  * 7 Min do Sonda Supermercados;
  * 8 Min da Estação Prefeito Celso Daniel Santo André;
  * 8 Min do Carrefour;
  * 13 Min do Centro de Santo André;
  * Fácil acesso às avenidas Industrial e Dom Pedro ||. 


#### Imagens
  * Foto Ilustrativa
  * Plantas
  * Vídeo tour 


  *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   * 

  *   *   *   * 

Áreas comuns
#### Diferenciais
  * Piscina Adulto
  * Piscina Infantil
  * Salão de Festas
  * Food Square
  * Cine Open Air
  * Bar Praia
  * Pub e Jogos
  * Quadra em Grama Sintética
  * Espaço Fitness
  * Fitness Externo
  * Bicicletário
  * Coworking
  * Sala Multiuso
  * Easy Market
  * Lavanderia
  * Office Space
  * Espaço Mulher
  * Brinquedoteca
  * Playground
  * Pet Care
  * Pet Place
  * Espaço de Convivência
  * Delivery

Ver todos
Lançamento
Piscina Adulto
Piscina Infantil
Salão de Festas
Fale com um corretor
×
#### Acompanhamento de obras
Mobiliz. Canteiro
100%
Fundação
35%
Estrutura
0%
Alvenaria
75%
Acabamento interno
5%
Acabamento externo
5%
Inst. Elétricas
0%
Inst. Hidráulicas
10%
Pintura
80%
Serv. Complementares
65%
  * Obras4 
  * 

Ver Vídeo
#### Localização
Stand de Vendas
#### Av Brigadeiro Faria Lima, 1740. São Paulo - SP
Veja como chegar
Waze Google Maps
Empreendimento
#### Av Paulista, 688, Cerqueira Cesar. São Paulo - SP
Veja como chegar
Waze Google Maps
Clique para exibir o mapa
Av Paulista , 688 - Cerqueira Cesar 
Av Brigadeiro Faria Lima , 1740 
#### Sobre a região
Com um desenvolvimento pautado na instalação de montadoras de veículos na região, ao longo da década de 60, Santo André começou a despontar economicamente e ser um dos destaques do Estado na geração de empregos, crescendo em ritmo acelerado também em setores como o de peças automotivas, eletrônicos, componentes para refrigeração, dentre outros.
Apesar disso, nos últimos anos, os setores comerciais e de serviços também foram se desenvolvendo e crescendo na cidade, fazendo com que Santo André continuasse com o status de uma das cidades que mais geram empregos em todo o Estado.
####  Imóveis relacionados 
Em Obras
#### Plantão para testes 2
Casa do Will
Texto de destaque
Em breve
#### Square Panamby Itapaiuna
Panamby
Square Panamby Itapaiuna
Em breve
#### Ar.que
Vila Buarques
Teste
Piscina Adulto com Cascata
Churrasqueira
Ccisa69 incorporação ltda (condomínio residencial dez jardim). Incorporação registrada em 15/10/2021, r.05 da matrícula 167.766 do 1º oficial de registro de imóveis de santo andré. Para mais informações, consulte a central de vendas da cury ( cnpj: 14.055.045/0001-78; ccisa 08 consultoria imobiliária ltda. - creci 23670-j). Responsável técnico ronaldo cury de capua.
* * *
Utilizamos cookies essenciais e tecnologias semelhantes e, ao continuar navegando, você concorda com estas condições.
Para mais informações, confira nossa Política de Privacidade e Política de cookies
OK
##### Sobre
  * Conheça a Cury
  * Regiões
  * Área do Cliente


##### Vendas
  * Imóveis
  * Simular Financiamento
  * Fale com um Corretor


##### Comunicação
  * Contato
  * Assessoria de Imprensa
  * Relações com Investidores


##### Cury nas redes
* * *
* * *
Cury Construtora e Incorporadora S/A 2025 - CRECI 24719-J. Todos os direitos reservados. 
Confira a nossa Política de Privacidade e Política de cookies
Ok
Ofereça seu terreno 
Quero vender meu terreno em: 
São Paulo Rio de Janeiro
Envie um e-mail para adefinir@cury.net com seu **nome** , **telefone** , **área do terreno** e **localização**. 
Ou se preferir, clique aqui   
para cadastrar o seu terreno 
Assessoria de Imprensa 
E-mail: cury@maquinacohnwolfe.com 
; 
Ok


# Liens externes trouvés
- https://cury.gupy.io/
- http://www.relacionamentocury.com.br/
- https://api.whatsapp.com/send?phone=5521999923476&text=Olá! Tenho interesse em saber mais sobre o imóvel Cury Jardim.
- https://www.youtube.com/watch?v=OUcn9Sq4dvM
- https://waze.com/ul?ll=-23.577328514843717,-46.686788260708404&navigate=yes
- https://maps.google.com/maps?daddr=-23.577328514843717,-46.686788260708404
- https://waze.com/ul?ll=-23.566565732727806,-46.6494593202319&navigate=yes
- https://maps.google.com/maps?daddr=-23.566565732727806,-46.6494593202319
- https://www.facebook.com/CuryConstrutora?fref=ts
- https://www.instagram.com/curyconstrutora/
- https://twitter.com/curyconstrutora
- https://www.youtube.com/user/curyconstrutora
- https://www.linkedin.com/company/cury-construtora/
- https://br.pinterest.com/curyconstrutoranet/
- https://www.tiktok.com/@curyconstrutora
- https://open.spotify.com/user/7ibqq6hybxooqerqc8ywnhqe9?si=5WTqJRxfRo6-3RoYe20vYA&nd=1
- adefinir@cury.net
  * Imóveis 
  * Cury 
  * Serviços 
  * Área do Cliente
  * São Paulo


  * São Paulo  Rio de Janeiro 


  * Imóveis 
Cury
  * Serviços
  *   * Área do Cliente 


Lançamento
Vila Maria
### Cury Mérito Vila Maria
2 dorms. 
Fale com um corretor
Fale com um corretor 
  * Sobre o imóvel
* * *
{ 
  * Imagens
* * *
  * Diferenciais
* * *
  * Mapa
* * *


Fale com um corretor 
  * Sobre o imóvel
* * *
  * Imagens
* * *
  * Diferenciais
* * *
  * Mapa
* * *


**Mérito Vila Maria.** Lazer completo pra você celebrar seus melhores momentos. 2 Dormitórios com opção de suíte, terraço e vaga de garagem coberta.
  * 3 Minutos da Universidade Uninove Vila Maria;
  * 4 Minutos do hospital Nossa Senhora do Rosário;
  * 11 Minutos do Expo Center Norte; 
  * Fácil acesso a Marginal Tietê, Av Salim Farah Maluf e Rod. Aryton Senna.


**Entre em contato com um consultor online e faça uma simulação.**
#### Imagens
  * Foto Ilustrativa
  * Plantas
  * Vídeo tour 


  *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   * 

  *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   * 

  *   *   *   *   *   *   *   * 

  *   *   *   *   *   *   *   * 

Áreas comuns
#### Diferenciais
  * Piscina Adulto
  * Piscina infantil
  * Churrasqueira
  * Salão de festas
  * Bar
  * Sala de descanso com sauna
  * Praça leitura
  * Pista de caminhada
  * Bicicletário
  * Fitness
  * Fitness Descoberto
  * Food Square
  * Quadra
  * Playground
  * Espaço Baby
  * Brinquedoteca
  * Sala de Jogos
  * Espaço Pet
  * Pet care
  * Office space
  * Easy Market
  * Oficina
  * Lavanderia
  * Espaço beleza
  * Piso laminado nos Dorms
  * Duplo acionamento nos vasos sanitários

Ver todos
Lançamento
Piscina Adulto
Piscina infantil
Churrasqueira
Fale com um corretor
×
#### Localização
Stand de Vendas
#### Rua Curuça, 649, Vila Maria. São Paulo - SP
Veja como chegar
Waze Google Maps
Empreendimento
#### Rua Curuça, 704, Vila Maria. São Paulo - SP
Veja como chegar
Waze Google Maps
Clique para exibir o mapa
Rua Curuça , 704 - Vila Maria 
Rua Curuça , 649 - Vila Maria 
#### Sobre a região
Quem busca imóveis na **Zona Norte de São Paulo** vai se surpreender com tudo o que a região pode oferecer. Além de excelentes bairros, a localidade também dispõe de facilidade de locomoção, ampla gama de comércios e variedade de lazer, que fazem com que ela seja ainda mais atrativa.
A Zona Norte está se desenvolvendo anualmente, seu crescimento é rápido e progressivo, o que faz com que cada vez mais pessoas elejam o local para viver em família ou, até mesmo, sozinhas.
####  Imóveis relacionados 
Em Obras
#### Green Lyne Pirituba
Pirituba
2 dorms, opção de terraço e lazer de clube
Piscina Adulto
Piscina infantil
Salão de festas
Churrasqueira
Em Obras
#### Blue Lyne Pirituba NOVO
Pirituba
2 dorms, opção de terraço e lazer de clube
Piscina infantil
Piscina Adulto
Churrasqueira
Salão de festas
Em Obras
#### Lyne Pirituba
Pirituba
2 dorms, lazer completo e opção de terraço
Piscina Adulto
Piscina infantil
Salão de festas
Fitness
Ccisa89 incorporadora ltda. (“condomínio residencial mérito vila maria”). O empreendimento só será comercializado após o registro de incorporação no cartório de imóveis competente, nos termos da lei nº. 4.591/64. Para mais informações, consulte a central de vendas da cury ( cnpj: 14.055.045/0001-78; ccisa 08 consultoria imobiliária ltda. - creci 23.670-j. Responsável técnico ronaldo cury de capua.
* * *
Utilizamos cookies essenciais e tecnologias semelhantes e, ao continuar navegando, você concorda com estas condições.
Para mais informações, confira nossa Política de Privacidade e Política de cookies
OK
##### Sobre
  * Conheça a Cury
  * Regiões
  * Área do Cliente


##### Vendas
  * Imóveis
  * Simular Financiamento
  * Fale com um Corretor


##### Comunicação
  * Contato
  * Assessoria de Imprensa
  * Relações com Investidores


##### Cury nas redes
* * *
* * *
Cury Construtora e Incorporadora S/A 2025 - CRECI 24719-J. Todos os direitos reservados. 
Confira a nossa Política de Privacidade e Política de cookies
Ok
Ofereça seu terreno 
Quero vender meu terreno em: 
São Paulo Rio de Janeiro
Envie um e-mail para adefinir@cury.net com seu **nome** , **telefone** , **área do terreno** e **localização**. 
Ou se preferir, clique aqui   
para cadastrar o seu terreno 
Assessoria de Imprensa 
E-mail: cury@maquinacohnwolfe.com 
; 
Ok
### Control your privacy
AdOpt
Our website uses cookies to improve navigation. Privacy Policy - Terms of use Developed by AdOpt
Customize Reject Accept


# Liens externes trouvés
- https://cury.gupy.io/
- http://www.relacionamentocury.com.br/
- https://api.whatsapp.com/send?phone=5521999923476&text=Olá! Tenho interesse em saber mais sobre o imóvel Cury Mérito Vila Maria.
- https://waze.com/ul?ll=-23.51327,-46.58969&navigate=yes
- https://maps.google.com/maps?daddr=-23.51327,-46.58969
- https://waze.com/ul?ll=-23.51380,-46.58945&navigate=yes
- https://maps.google.com/maps?daddr=-23.51380,-46.58945
- https://www.facebook.com/CuryConstrutora?fref=ts
- https://www.instagram.com/curyconstrutora/
- https://twitter.com/curyconstrutora
- https://www.youtube.com/user/curyconstrutora
- https://www.linkedin.com/company/cury-construtora/
- https://br.pinterest.com/curyconstrutoranet/
- https://www.tiktok.com/@curyconstrutora
- https://open.spotify.com/user/7ibqq6hybxooqerqc8ywnhqe9?si=5WTqJRxfRo6-3RoYe20vYA&nd=1
- adefinir@cury.net
- https://goadopt.io/en/porque-aviso/?utm_content=main&utm_medium=cookie_banner_web&utm_source=cookie_banner_d44972e9-1283-4d1b-b2de-6c0653a2c941
- https://hub.goadopt.io/document/2d556213-4359-44cf-a319-278f1de4e405
- https://hub.goadopt.io/document/b059c8cf-5787-49fc-9c2a-d24fd98d1b2f
  * Imóveis 
  * Cury 
  * Serviços 
  * Área do Cliente
  * São Paulo


  * São Paulo  Rio de Janeiro 


  * Imóveis 
Cury
  * Serviços
  *   * Área do Cliente 


Lançamento
Mooca
### Cury Cidade Mooca
2 dorms. 
Fale com um corretor
Fale com um corretor 
  * Sobre o imóvel
* * *
{ 
  * Imagens
* * *
  * Diferenciais
* * *
  * Mapa
* * *


Fale com um corretor 
  * Sobre o imóvel
* * *
  * Imagens
* * *
  * Diferenciais
* * *
  * Mapa
* * *


More na Mooca! Apartamentos de 2 dormitórios, com opção de terraço e lazer diferenciado.
  * Ao lado da estação Juventus Mooca
  * Próximo do Hospital Sancta Maggiore Mooca 
  * Universidade Anhembi Morumbi
  * Estação Brás
  * Fácil acesso as avenidas: Do Estado, Radial Leste e 23 de Maio. 


**Fale agora mesmo com um dos nossos corretores online e Saiba Mais.**
#### Imagens
  * Decorado
  * Foto Ilustrativa
  * Plantas
  * Vídeo tour 


  *   *   *   *   *   *   *   * 

  *   *   *   *   *   *   *   * 

  *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   * 

  *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   * 

  *   *   *   *   *   *   * 

  *   *   *   *   *   *   * 

Áreas comuns
#### Diferenciais
  * Piscina Adulto
  * Piscina Infantil
  * Redário
  * Churrasqueira
  * Sala de Descanso com Sauna
  * Home Office
  * Praça de Convivência
  * Lavanderia
  * Playground
  * Quadra Gramada
  * Sala de Jogos
  * Sport Bar
  * Brinquedoteca
  * Food Square
  * Fitness Externo
  * Fitness
  * Pet Place
  * Pet Care
  * Oficina
  * Bicicletário
  * Piso Laminado nos Quartos
  * Arejadores nas Torneiras
  * Duplo Acionamento nos Vasos Sanitários

Ver todos
Lançamento
Piscina Adulto
Piscina Infantil
Redário
Fale com um corretor
×
#### Localização
Stand de Vendas
#### Rua da Mooca, 1290, Mooca. São Paulo - SP
Veja como chegar
Waze Google Maps
Empreendimento
#### Rua da Mooca, 1290, Mooca. São Paulo - SP
Veja como chegar
Waze Google Maps
Clique para exibir o mapa
Rua da Mooca , 1290 - Mooca 
#### Sobre a região
A **Zona Leste de São Paulo** é perfeita para quem procura um lugar para viver com qualidade e muitas possibilidades. O local se destaca por ocupar o segundo lugar no ranking de melhor região para morar na cidade de São Paulo. Com uma área de 326 km², ela também está entre as mais populosas da capital: quase cinco milhões de habitantes.
A Zona Leste é contemplada por bairros com altos índices de desenvolvimento, como Mooca, Belém, Tatuapé, Vila Prudente e Água Rasa.
####  Imóveis relacionados 
Lançamento
#### Cury Cidade Mooca Vila Palermo
Mooca
2 e 3 quartos com varanda, opção de suíte e lazer completo
Piscina Adulto
Piscina infantil
Churrasqueira
Cine Open Air
Em Obras
#### Cury Único Jacu Pêssego
São Miguel
2Dorms, com ou sem sacada, lazer diferenciado
Easy Market
Churrasqueira
Salão de festas
Campo Gramado
Em Obras
#### Cury Dez São Miguel 2
São Miguel
2 Dorms com e sem vaga e amplo lazer
Fitness
Churrasqueira
Salão de festas
Fitness/ Sala de ginástica
Ccisa66 incorporação ltda. (condomínio residencial cidade mooca vila capri). O empreendimento só será comercializado após o registro de incorporação no cartório de imóveis competente, nos termos da lei nº. 4.591/64. Para mais informações, consulte a central de vendas da cury (cnpj: 14.055.045/0001-78; ccisa 08 consultoria imobiliária ltda. - creci 23.670-j). ). Responsável técnico ronaldo cury de capua.
* * *
Utilizamos cookies essenciais e tecnologias semelhantes e, ao continuar navegando, você concorda com estas condições.
Para mais informações, confira nossa Política de Privacidade e Política de cookies
OK
##### Sobre
  * Conheça a Cury
  * Regiões
  * Área do Cliente


##### Vendas
  * Imóveis
  * Simular Financiamento
  * Fale com um Corretor


##### Comunicação
  * Contato
  * Assessoria de Imprensa
  * Relações com Investidores


##### Cury nas redes
* * *
* * *
Cury Construtora e Incorporadora S/A 2025 - CRECI 24719-J. Todos os direitos reservados. 
Confira a nossa Política de Privacidade e Política de cookies
Ok
Ofereça seu terreno 
Quero vender meu terreno em: 
São Paulo Rio de Janeiro
Envie um e-mail para adefinir@cury.net com seu **nome** , **telefone** , **área do terreno** e **localização**. 
Ou se preferir, clique aqui   
para cadastrar o seu terreno 
Assessoria de Imprensa 
E-mail: cury@maquinacohnwolfe.com 
; 
Ok
### Control your privacy
AdOpt
Our website uses cookies to improve navigation. Privacy Policy - Terms of use Developed by AdOpt
Customize Reject Accept


# Liens externes trouvés
- https://cury.gupy.io/
- http://www.relacionamentocury.com.br/
- https://api.whatsapp.com/send?phone=5521999923476&text=Olá! Tenho interesse em saber mais sobre o imóvel Cury Cidade Mooca.
- https://waze.com/ul?ll=-23.554446,-46.612654&navigate=yes
- https://maps.google.com/maps?daddr=-23.554446,-46.612654
- https://www.facebook.com/CuryConstrutora?fref=ts
- https://www.instagram.com/curyconstrutora/
- https://twitter.com/curyconstrutora
- https://www.youtube.com/user/curyconstrutora
- https://www.linkedin.com/company/cury-construtora/
- https://br.pinterest.com/curyconstrutoranet/
- https://www.tiktok.com/@curyconstrutora
- https://open.spotify.com/user/7ibqq6hybxooqerqc8ywnhqe9?si=5WTqJRxfRo6-3RoYe20vYA&nd=1
- adefinir@cury.net
- https://goadopt.io/en/porque-aviso/?utm_content=main&utm_medium=cookie_banner_web&utm_source=cookie_banner_d44972e9-1283-4d1b-b2de-6c0653a2c941
- https://hub.goadopt.io/document/2d556213-4359-44cf-a319-278f1de4e405
- https://hub.goadopt.io/document/b059c8cf-5787-49fc-9c2a-d24fd98d1b2f
  * Imóveis 
  * Cury 
  * Serviços 
  * Área do Cliente
  * São Paulo


  * São Paulo  Rio de Janeiro 


  * Imóveis 
Cury
  * Serviços
  *   * Área do Cliente 


Lançamento
Mooca
### Cury Cidade Mooca Vila Palermo
Studio 
Fale com um corretor
Fale com um corretor 
  * Sobre o imóvel
* * *
{ 
  * Imagens
* * *
  * Diferenciais
* * *
  * Mapa
* * *
  * Obras
* * *


Fale com um corretor 
  * Sobre o imóvel
* * *
  * Imagens
* * *
  * Diferenciais
* * *
  * Mapa
* * *
  * Obras
* * *


More na Mooca! Apartamentos de 2 dormitórios, com opção de terraço e lazer diferenciado.
  * Próximo as estações da Luz, Juventus e Bresser. 
  * Próximo do Hospital Sancta Maggiore Mooca
  * Universidade Anhembi Morumbi
  * Estação Brás
  * Fácil acesso as avenidas: Do Estado, Radial Leste e 23 de Maio.


Fale agora mesmo com um dos nossos corretores online e Saiba Mais.
#### Imagens
  * Foto Ilustrativa
  * Plantas
  * Vídeo tour 


  *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   * 

  *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *   * 

  *   *   *   *   *   * 

  *   *   *   *   *   * 

Áreas comuns
#### Diferenciais
  * Piscina Adulto
  * Piscina infantil
  * Churrasqueira
  * Cine Open Air
  * Quadra Gramada
  * Espaço Games
  * Salão de Festas
  * Sauna
  * Sport Bar
  * Food Square
  * Praça de Convivência
  * Redário
  * Fitness
  * Fitness externo
  * Bicicletário
  * Playground
  * Brinquedoteca
  * Easy Market
  * Lavanderia*
  * Home Office
  * Oficina
  * Pet Place
  * Pet Care
  * Piso Laminado nos Dorms
  * Duplo Acionamento nos Vasos Sanitários
  * Arejadores nas Torneiras

Ver todos
Lançamento
Piscina Adulto
Piscina infantil
Churrasqueira
Fale com um corretor
×
#### Acompanhamento de obras
Mobiliz. Canteiro
10%
Fundação
30%
Estrutura
20%
Alvenaria
50%
Acabamento interno
40%
Acabamento externo
70%
Inst. Elétricas
60%
Inst. Hidráulicas
90%
Pintura
80%
Serv. Complementares
20%
  *   *   *   * Imagem aberta 1 
  * Imagem aberta 2 
  * Imagem aberta 3 
  *   * 

Ver Vídeo
#### Localização
Stand de Vendas
#### Rua da Mooca, 1290, Mooca. São Paulo - SP
Veja como chegar
Waze Google Maps
Empreendimento
#### Rua da Mooca, 1290, Mooca. São Paulo - SP
Veja como chegar
Waze Google Maps
Clique para exibir o mapa
Rua da Mooca , 1290 - Mooca 
#### Sobre a região
A **Zona Leste de São Paulo** é perfeita para quem procura um lugar para viver com qualidade e muitas possibilidades. O local se destaca por ocupar o segundo lugar no ranking de melhor região para morar na cidade de São Paulo. Com uma área de 326 km², ela também está entre as mais populosas da capital: quase cinco milhões de habitantes.
A Zona Leste é contemplada por bairros com altos índices de desenvolvimento, como Mooca, Belém, Tatuapé, Vila Prudente e Água Rasa.
####  Imóveis relacionados 
Lançamento
#### Cury Cidade Mooca
Mooca
2 dorms, opção de terraço, lazer diferenciado
Piscina Adulto
Piscina Infantil
Redário
Churrasqueira
Em Obras
#### Cury Único Jacu Pêssego
São Miguel
2Dorms, com ou sem sacada, lazer diferenciado
Easy Market
Churrasqueira
Salão de festas
Campo Gramado
Em Obras
#### Cury Dez São Miguel 2
São Miguel
2 Dorms com e sem vaga e amplo lazer
Fitness
Churrasqueira
Salão de festas
Fitness/ Sala de ginástica
Ccisa 66 incorporação ltda. (condomínio residencial cidade mooca vila palermo). Incorporação registrada em 04/01/2022, r. 03 da matrícula 212.253 do 7º oficial de registro de imóveis de são paulo. ). Responsável técnico ronaldo cury de capua.
* * *
Utilizamos cookies essenciais e tecnologias semelhantes e, ao continuar navegando, você concorda com estas condições.
Para mais informações, confira nossa Política de Privacidade e Política de cookies
OK
##### Sobre
  * Conheça a Cury
  * Regiões
  * Área do Cliente


##### Vendas
  * Imóveis
  * Simular Financiamento
  * Fale com um Corretor


##### Comunicação
  * Contato
  * Assessoria de Imprensa
  * Relações com Investidores


##### Cury nas redes
* * *
* * *
Cury Construtora e Incorporadora S/A 2025 - CRECI 24719-J. Todos os direitos reservados. 
Confira a nossa Política de Privacidade e Política de cookies
Ok
Ofereça seu terreno 
Quero vender meu terreno em: 
São Paulo Rio de Janeiro
Envie um e-mail para adefinir@cury.net com seu **nome** , **telefone** , **área do terreno** e **localização**. 
Ou se preferir, clique aqui   
para cadastrar o seu terreno 
Assessoria de Imprensa 
E-mail: cury@maquinacohnwolfe.com 
; 
Ok
### Control your privacy
AdOpt
Our website uses cookies to improve navigation. Privacy Policy - Terms of use Developed by AdOpt
Customize Reject Accept


# Liens externes trouvés
- https://cury.gupy.io/
- http://www.relacionamentocury.com.br/
- https://api.whatsapp.com/send?phone=5521999923476&text=Olá! Tenho interesse em saber mais sobre o imóvel Cury Cidade Mooca Vila Palermo.
- https://www.youtube.com/watch?v=E6JwxgtGapA
- https://waze.com/ul?ll=-23.55459,-46.61272&navigate=yes
- https://maps.google.com/maps?daddr=-23.55459,-46.61272
- https://www.facebook.com/CuryConstrutora?fref=ts
- https://www.instagram.com/curyconstrutora/
- https://twitter.com/curyconstrutora
- https://www.youtube.com/user/curyconstrutora
- https://www.linkedin.com/company/cury-construtora/
- https://br.pinterest.com/curyconstrutoranet/
- https://www.tiktok.com/@curyconstrutora
- https://open.spotify.com/user/7ibqq6hybxooqerqc8ywnhqe9?si=5WTqJRxfRo6-3RoYe20vYA&nd=1
- adefinir@cury.net
- https://goadopt.io/en/porque-aviso/?utm_content=main&utm_medium=cookie_banner_web&utm_source=cookie_banner_d44972e9-1283-4d1b-b2de-6c0653a2c941
- https://hub.goadopt.io/document/2d556213-4359-44cf-a319-278f1de4e405
- https://hub.goadopt.io/document/b059c8cf-5787-49fc-9c2a-d24fd98d1b2f